### ISSUE TITLE
Grillmaster / BBQ

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#10]
On Saturday evening we would like to have a BBQ and we need somebody to organize that.

I was thinking of @schorsch ;)   Maybe @salesking might also be interested in sponsoring this?

**Comment by raucao** [comment]
Brätel Galore!

**Comment by schorsch** [comment]
Yes i'm in for it. Would need the number of peoples involved

**Comment by jhilden** [comment]
Awesome!  We are planning to have 200 ppl there.   The Kletterhalle already has one Gasgrill that we could rent, but I don't know how big it is.

**Comment by thilo** [comment]
costs would be interesting aswell.

**Comment by jhilden** [comment]
here is a pic of the grill they have ![grill](https://dl.dropboxusercontent.com/u/409736/railscamp_venue/2013-06-07%2010.02.34.jpg)

I guess we probably also need another one.

@schorsch could you maybe make a rough calculation of the costs, so we can start talking to sponsors?  Maybe you can also look for somebody to help you.  Any volunteers?

**Comment by thegcat** [comment]
I might be able to provide another one, roughly the same size, coal-powered. As it would need to be transported from Dortmund, I'd rather count it as a joker if everything else fails.

**Comment by raucao** [comment]
I'd vote for getting proper grass-fed meat or poultry directly from a farm. It's less expensive than it sounds:

http://www.freilandhof.com/produkte-bestellung/
http://www.naturlandhof-buening.de/html/produkt_preisliste.html

Maybe we can get discounts for our large order.

Anybody knows how many vegetarians to expect? Any ideas how to make the BBQ nice for them as well?

**Comment by tandibar** [comment]
We could also order Burgers from Freddy Schilling (http://www.freddyschilling.de) :-) They give you everything you need to build their Burgers on your own.

**Comment by raucao** [comment]
Please always add prices when suggesting these things. Otherwise we cannot vote/decide on it. Can you ask them?

**Comment by tandibar** [comment]
Just got a price: one Burger (all inclusive) for 8,70 EUR. I think this idea died in this very moment...

**Comment by raucao** [comment]
Yup. :)

One kg grass-fed organic Schnitzel costs like 10-12 bucks.

**Comment by galfert** [comment]
I can come up with some options for the vegetarians. I'm not a big fan of the typical "Fleischersatzprodukte", so I would rather prepare some stuff with vegetables, cheese and so on. Does the location have a kitchen that we can use?

Would be good to know the broad number of vegetarians and if we also need some vegan options. But I think that's already a question in the survey.

**Comment by jhilden** [comment]
Yes there is a kitchen at the venue.  Anything in particular you need?  Then I could check if it's there, the next time I'm at the venue.

**Comment by jhilden** [comment]
btw:  We really need some (at least rough) calculations for the BBQ, so we can plan the budget for the event.  Would be great if somebody could produce some numbers.

**Comment by raucao** [comment]
Well, we just need to know how much meat to get and what else we provide. The numbers for meat can be derived from the links I posted e.g., although I'm sure we can get a discount for ordering so much at once.

**Comment by galfert** [comment]
I don't need anything special. Just a proper knife and maybe 1-2 larger bowls.

**Comment by schorsch** [comment]
@jakob i talked to Tatijana and we estimated 380-450 € based on our last
happenings. I scheduled to go shopping at handelshof on friday afternoon
and will to prepare the Rostbrätl afterwards.

The list so far:
- ~100 pcs of pork -> converted to rostbrätl + Onions, Beer, Mustard
- 100-150 Bratwurst
- Corn for our veggies
- Salad's ???

2013/7/4 Garret Alfert notifications@github.com

**Comment by galfert** [comment]
Can someone tell me the number of vegetarians from the survey? Then I will come up with what and how much I need for the veggie options.

**Comment by jhilden** [comment]
These are the numbers from the survey:

```
Omnivore (SQ004)    27  61.36%    
Vegetarian (SQ001)  5   11.36%    
Vegan (SQ002)   1   2.27%     
Low carb (SQ003)    6   13.64%    
```

Other restrictions:
- Bacotarian
- nut allergy
- Laktose-intolerant
- No frutti di Mare and no insides

@galfert some numbers for the budget would be really good!

**Comment by schorsch** [comment]
es wird gegessen was auf den tisch kommt!

2013/7/15 Jakob Hilden notifications@github.com

**Comment by galfert** [comment]
Hier mal meine Berechnungen für gefüllte Riesenchampignons und Gemüsespieße. Habe 20 Personen angesetzt. Ich denke das sollte reichen, oder? Und was übrig bleibt kann ja auch als Beilage zur Bratwurst gereicht werden. Ist sogar alles Low Carb ;)
- 20 Riesenchampignons
- 500g Cherrytomaten
- 9 Paprika
- 6 Zucchinis
- 3 Auberginen
- 3 Zwiebeln
- 2 Gemüsezwiebeln
- 3 Becher (à 200g) Crème Fraiche
- 3 Packungen (à 250g) geriebenen Käse (Edamer, Emmentaler oder Gouda)
- 3 Packungen (à 40g) Basilikum (gehackt aus der Tiefkühltruhe)
- 20 Spieße
- 1 Fl. Olivenöl
- Rosmarin
- Thymian
- Salz
- Pfeffer

@schorsch Bist du 'n Schätzelein und bringst mir das von deiner Einkaufstour beim Handelshof mit?

Die Preiseinschätzung für's Budget reiche ich nachher noch nach. Muss später selbst noch einkaufen und da kann ich dann die fehlenden Preise nachsehen.

**Comment by schorsch** [comment]
auf der liste

Am 17. Juli 2013 15:32 schrieb Garret Alfert notifications@github.com:

**Comment by galfert** [comment]
@jhilden Preislich komme ich für's Veggie BBQ auf insgesamt knapp 50 Euro.

**Comment by thilo** [comment]
@schorsch satt das wir ne Rechung an Sales King stellen und davon denn die
Zutaten kaufen kann du die auch einfach auf SalesKing
Rechnung kaufen? spart verwaltung und kommt aufs selbe raus.

**Comment by schorsch** [comment]
@thilo geht leider nicht so einfach weil ich nicht das ganze BBQ bezahle.
Ich will mir auch keine gedanken machen auf welche firmen, welcher teil der
rechnung geht und ob diese firmen auch handelshofkarten haben.

Schreib mir eine Rechnung über 150€ sponsoring, gebt mir eine
handelshofkarte und cash oder cc über das budget.
btw. Tatjana kommt mit und bei den bisherigen events haben wir das über RL
abgewickelt.

Am 18. Juli 2013 14:26 schrieb Thilo Utke notifications@github.com:

**Comment by Uepsilon** [comment]
Könnt ihr bitte Becher für das Wasser mitbringen?

**Comment by jhilden** [comment]
@galfert @schorsch  We can use the kitchen at the venue and they have a limited supply of kitchenware, bowls etc.  We just have to make sure that we clean the kitchen afterwards.

**Comment by raucao** [comment]
Yay. Will also make a salad or two.

**Comment by galfert** [comment]
Great. I forgot to ask if they have a pan. If not, can one of the locals bring one, please?

**Comment by jhilden** [comment]
We'll find out tomorrow.
