### ISSUE TITLE
Session planning

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#11]
We need somebody to manage the session planning.  Since we are expecting 200 participants we probably need to prepare the session planning in advance somehow.  

Maybe http://www.timetabler.de/ by @startupbus could be the base for a solution for that.

**Comment by raucao** [comment]
We can use Lanyrd for the session schedule. I claimed the event, which means we can add rooms and have a proper schedule with overview, time slider, etc.

**Comment by moonglum** [comment]
I would like to help with that :smile:

**Comment by raucao** [comment]
@moonglum Nice! I'll get you access to the activities app by the eurucamp guys, when it's ready. I have a feeling we could use/extend it for our session planning.

**Comment by moonglum** [comment]
@skddc Sounds great :smile:

**Comment by jhilden** [comment]
I created a pad for a rough idea for an schedule for the weekend:  http://titanpad.com/yqE49QM7n6

feedback welcome.

**Comment by moonglum** [comment]
I now have access to the eurucamp activity app (we're allowed to use it :cat:) , it's great and IMHO be usable for both activity and session planning (I don't think we should even distinguish between activities and sessions). I hope to get some time soon to look into that in more detail.

**Comment by jhilden** [comment]
Very cool.  Maybe you can show me tomorrow at the SIGINT?

**Comment by raucao** [comment]
> I don't think we should even distinguish between activities and sessions

We didn't plan to. Let's all meet at SigInt and have a look! :)

**Comment by moonglum** [comment]
Agreed :rocket:

**Comment by raucao** [comment]
What's the current status? The app is very buggy, but we should start adding sessions asap.

**Comment by moonglum** [comment]
I will try to get some stuff done on Sunday. Can't really work on it before though :unamused: Maybe some people can hack on it tomorrow as @jhilden suggested?

**Comment by jhilden** [comment]
I'm down.  Who else?

**Comment by jhilden** [comment]
@skade could you make me an admin for the repository so I can add 1-2 more people tomorrow if need be?  That would be awesome.

**Comment by skade** [comment]
@jhilden I trust you to be sane people and gave the Railscamp DE team adminstrative for the next few days.

**Comment by jhilden** [comment]
Thanks a lot @skade.  We will be very sane and mostly stay within the `railscamp_germany` branch.

**Comment by moonglum** [comment]
I guess there are still a few tweaks to do, but it's usable :wink: Did you already announce it officially?
