### ISSUE TITLE
Venue, power, chairs, "Hausmeister"

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#13]
I will try to take care of working with the venue to sort out all the requirements we have for the location.
- [ ] power outlets
- [ ] chairs
- [ ] maybe a hacker tent in front of the building  => #16

**Comment by DonSchado** [comment]
150 Chairs at the location, do we need more?

**Comment by raucao** [comment]
Maybe 50 more, if it's not too much hassle.

**Comment by jhilden** [comment]
@koos will check if we can get Mehrfachstecker from Dingfabrik.  And we can bring some from Railslove/CowoCo

@schorsch will bring a Kabeltrommel

**Comment by thegcat** [comment]
Ich frage mal einen bekannten Elektromeister.

**Comment by raucao** [comment]
150 chairs might be enough afterall, because our beer garden doesn't have to be so large. Right?

**Comment by jhilden** [comment]
I think so, too

**Comment by thegcat** [comment]
So, der bekannte Elektromeister könnte uns was leihen, auch Drehstrom falls vorhanden bzw. notwendig.

Wie sieht's z.B. in den größeren Räumen mit Starkstromanschluß aus? Sollen wir da mittig dann eine größere Verteilerdose rein tun? Wer hat da einen Überblick und könnte mal überschlagen, was wir brauchen?

**Comment by jhilden** [comment]
Verteiler von den Starkstromanschlüssen sind vorhanden.  Wir sollten nur guckn, dass wir genug Mehrfachstecker haben und vielleicht noch 1-2 Kabeltrommeln.
