### ISSUE TITLE
Camera Equipment

### ISSUE THREAD

**Issue by moonglum** [railscamp/railscamp-germany-2013#15]
As @bitboxer just reminded me: We may want to record talks etc. He recommended [DV Kameraverleih](http://dv-kameraverleih.de/) where you can get a "professional equipment for 40 Euro a day" :smile:

**Comment by bitboxer** [comment]
I would vote for: 
- Sony HDR-FX1000  (EUR 22,-/Tag), a real work horse. Everyone uses those.
- Some Tapes or Laptop with Firewire and enough disc space
- Vinten PRO-5 (EUR 4,-/Tag)
- Mics and other cables

BUT: get at least a day of training on the camera under real conditions. This is not a kids toy and needs to be setup correctly to get the best recordings.

**Comment by a2800276** [comment]
Is this necessary? I've never been able to watch more than 5 minutes of a recorded conference talk, somehow they're much more compelling IRL. €22/day is just the camera. Unless the setup is REALLY professional, videos are edited aftwards and spliced together with dedicated screen feeds, I don't think this is necessary.

**Comment by bitboxer** [comment]
Do your speakers a favor and record the talks. A lot of people watch them. Just look at the view counts of the confreaks videos. And even professional Videos are edited afterwards. And 22€/day is fucking cheap. That equipment costs thousands of euros.

**Comment by raucao** [comment]
It's a marginal share of the whole budget, so I'd say if somebody wants to be responsible for it, set it up and operate it (_and_ edit it afterwards or find someone to do it), go for it! Let's just not get the equipment without anyone having committed to actually using it.

**Comment by jhilden** [comment]
+1 for what @skddc said

**Comment by code-later** [comment]
I agree with @skddc and I think your totally underestimating the amount of work for this to be done, @bitboxer. If someone really feels like doing this and has the required time and experience, yes this would be pretty awesome!

**Comment by bitboxer** [comment]
No, I don't underestimate it. It is LOT of work. BUT it would be worth it. Sadly I can't do it, because I moved to Berlin last week and need to get some stuff done here :sob:

**Comment by code-later** [comment]
I didn't say it would not be worth it, I just wanted to stress the workload again to prevent, that someone wants to do it just to realize in the end that it is just too much work. And that would be very sad.

**Comment by code-later** [comment]
I have another proposal which has something to do with this issue:

My wife is a freelancing journalist and would like to make some kind of short movie about the camp. It is very likely it will get sold, but who knows. The result would mainly be some demo for her and I think it would be a great summary of the event. It would include impressions from all parts of the camp and of course some interviews. She would bring the entire equipment.

What do you think about this?

**Comment by raucao** [comment]
Sounds fantastic to me!

**Comment by jhilden** [comment]
Super fantastic!

**Comment by moonglum** [comment]
Yes of course!

**Comment by code-later** [comment]
I have bad news on this one, unfortunately my wife cannot make. She worked a little bit too much the last weeks and really need this weekend off. Thus I prohibited her to come along a work again ;-) It's a bit sad, but I guess we still can do some GoPro action shots.

Sorry for any inconvenience.

**Comment by code-later** [comment]
And I would just close this issue.
