### ISSUE TITLE
Hacker tent

### ISSUE THREAD

**Issue by raucao** [railscamp/railscamp-germany-2013#16]
Something similar to the RailsBerry tent. Or maybe macgyver us sth.

**Comment by jhilden** [comment]
Looked up some prices.  Here it would be 400-900€ http://mpk24.de/100

**Comment by raucao** [comment]
Bull riding und Hüpfkissen! :)

**Comment by jhilden** [comment]
"Railscamp - Cowboy Edition".   Yieeeha!   :cow: :circus_tent: :gun:

**Comment by raucao** [comment]
By the way, we need to have a proper football table! Maybe in the tent?

**Comment by jhilden** [comment]
foosball table => #21

**Comment by tatjanala** [comment]
I just booked two 4*6m tents for 480€. They will bring it Friday afternoon 4 pm and set it up, Monday afternoon they'll remove it.  We have to pay cash, they'll bring an invoice.

**Comment by moonglum** [comment]
Awesome, @tatjanala :+1:

Do we have fat boys etc. for inside the tent? :wink:

**Comment by jhilden** [comment]
We have a couple fatboys (like 3 or so) from Cowoco and we should get Liegestühle from AdCloud.
