### ISSUE TITLE
Coffee

### ISSUE THREAD

**Issue by moonglum** [railscamp/railscamp-germany-2013#17]
We need Coffee for the conference.

**Comment by raucao** [comment]
![overcaffeinated](https://f.cloud.github.com/assets/842/573555/a320e600-c7b3-11e2-9161-9633fbac4948.gif)

**Comment by tmschndr** [comment]
Can we afford a Van Dyck Barista again, like we had during Rails Girls? http://www.vandyckkaffee.de/espressobike1.html

**Comment by jhilden** [comment]
@tmschndr can you get us a price for the barista?  Then we can certainly ask around if we can find a coffee sponsor

**Comment by tmschndr** [comment]
@tatjanala might help with that. think she handled it last time. I'll ask her to put numbers in here.

**Comment by tatjanala** [comment]
At the RailsGirls event we paid 480€ for one day, 150-200 cups of coffee included. I don't think it makes a difference if we book the espressobike or just a barista.

**Comment by moonglum** [comment]
I promised to get information about the baristas at NoSQL Matters, here you are:

> Jörg Studt
> barista to go CaffèCatering
> 
> Wittgensteinstraße 30
> 50931 Köln
> 
> +49 (0) 221 44 90 51 13
> +49 (0) 176 96 89 31 82
> 
> info@barista-to-go.de
> www.barista-to-go.de

**Comment by erdnusskeks** [comment]
What about the coffee you served at interactive cologne? Was it also a Van Dyck barista? The Soy Latte was delicious! : )

**Comment by raucao** [comment]
This issue could use a coffee geek. I hate to say it, but the one at IA was standard overroasted stuff. Totally drinkable, but not the real thing.

**Comment by bascht** [comment]
As I took home the coffee hat from last weeks cologne.rb I might chime in here, as well I guess.
I contacted a friend of mine, who works at a cologne coffee roastery and also happens to be a trained barista. So when worse comes to worse we could also arrange to have him over at railscamp to build some fresh brews. ;-)

**Comment by jhilden** [comment]
@bascht Why only "when worst comes to worst"?  That option sounds good to me. Just get us a price and make it happen.

**Comment by bascht** [comment]
@jhilden I'll get back to as soon as I have any news. ;)

**Comment by bascht** [comment]
Alright - got feedback from [Die Rösterei](http://www.moxxacaffe.de/die-roesterei-koeln.html), but a the moment they don't have a fixed price model. The could send a bike, but it would be pay-as-you go. So, maybe I am late to the party - but: 
- Do we have real numbers for coffee-budget, yet?
- Do we want the fancy latte art / espresso machine stuff or: plain coffee?

At a rate of 480€ / day we could surely arrange to buy a sufficient amount of decent coffee and I could ask a friend to orchestrate a couple of chemexes, no?

**Comment by raucao** [comment]
We're still looking for a coffee sponsor. Would be easier if we knew how much it costs.

**Comment by bascht** [comment]
So, any news on the "coffee sponsor" front? Otherwise this turns out to be a chicken-and-egg problem. 

@jhilden I could probably arrange to have a friend come over - so this would be more like a personal favour - nothing I could get a quote or a proper invoice for.

**Comment by raucao** [comment]
It's not really chicken-and-egg. We should be able to get a quote, and then we have something concrete to plan with in terms of budget. Maybe we don't need a separate sponsor, if we have room in the overall budget for example.

**Comment by bascht** [comment]
Good news from my side: I finally got a fixed price quote from »Die Rösterei« – They could send a small coffee "truck" and would charge us 500 € / day - which would include a coffee flatrate for the day. If we manage to drink more than they calculated they'd be ok to "sponsor" the remainder. 

##### Goodie:
- From what they told me, the car has a built in Crêpe unit - they wont be included in the price, though. ;)

##### Some questions are left:
- As it is not a bike, but a complete car: Is there any space inside the venue?
- The car has built in water tanks, but it would be good to have fresh drinking water near the location…
- Can they bring a banner (probably a stand-up display from the coffee roasting house)

## 

![dscn0866_376](https://f.cloud.github.com/assets/51264/769356/7440c0a0-e8b3-11e2-838c-41855dea0dc1.jpg)

**Comment by moonglum** [comment]
Sounds awesome!! :dancer: I hope we have enough space :pray:

**Comment by bascht** [comment]
So - @jhilden, @skddc  – who will ask the sponsors?

**Comment by raucao** [comment]
I'll write another blog post for new sponsors and then we should send emails directly to more prospects.

**Comment by jhilden** [comment]
@bascht we are on it to find sponsors for the cofee.  Thanks for getting the prices for us. When do you need to make the reservation final?

We definitely have enough space to drive the car into the hall or it could also park behind it.  I don't think water supply should be a problem.

**Comment by bascht** [comment]
Well - as there is not much time left  - would it be possible to fix a deal this week?

**Comment by jhilden** [comment]
@bascht please fix the deal.

We haven't found dedicated coffee sponsor(s) yet, but we still have a couple of days left. Anybody any ideas?

The current estimate for the final participant count is something like 130-150 ppl. could you ask if that could make the price a little bit cheaper?  500€ seems a little much if you take into account that there are also people who don't drink any coffee (e.g. me).   If they can give us a little better price they can definitely also bring along their banner.

**Comment by raucao** [comment]
Yes, seems a bit much to me as well, given the assumption that probably even half the people don't drink coffee, especially when there's tons of Club Mate around.

**Comment by bascht** [comment]
The price was based on the number 200 - I just gave them a call:
- They'd make it 400€/day for a flat rate. 
- They will bring  a banner
- We should decide if we want Crêpe (not included in the price)

As there are only 5 days left, I'd rather not dither any longer: **Yay or Nay?**

**Comment by jhilden** [comment]
400€ still sounds a bit much to me as a non coffee drinker, especially considered that we'll probably have 40% less participants (calculating with 120) but they reduced the price only by 20% and they get a banner.  Maybe we can get another 50€/day reduction for a friendly non-profit event? :rabbit: 

But since we :heart: coffee drinkers so much, it's defintely a **Yay** :thumbsup: 

(since there was no interest in Crepe, let's not take that)

**Comment by raucao** [comment]
> They'd make it 400€/day for a flat rate

Let's hope the coffee is good then. :)

**Comment by bascht** [comment]
Alright then. I call him to make the deal. Not sure if we need it beforehand, but:

Who will be invoiced to? Is it the ruby berlin e.V.? 
When should the car arrive on saturday?

**Comment by jhilden** [comment]
yes, invoice will go to Ruby Berlin e.V.:  http://rubyberlin.org/imprint

I would say the car should be ready to serve coffee by Saturday 10:00 the latest.  The campers sleeping the the skate hall will probably need it ;)

**Comment by bascht** [comment]
_Sealed at 400._ (We're not really going bankrupt b/c of 50€, are we? :money_with_wings: )

They'll arrive at ~ 09:30 on saturday and have my number. I guess I'll be around the venue at around nine-ish.

**Comment by raucao** [comment]
FYI: We just found a sponsor for this.

**Comment by raucao** [comment]
@bascht I need a phone number of the company, so the sponsor can give them a call and figure out how to best brand the thing.

**Comment by bascht** [comment]
:speech_balloon: `-- off the record --`

**Comment by sschiffer** [comment]
hey guys, 
i'll attend the camp representing InVision (coffee sponsor) from Saturday afternoon until the very end... Tomorrow morning a colleague of mine will be at the venue to decorate the coffee place a bit... If you need any further details, just give me a shout...
