### ISSUE TITLE
Reception

### ISSUE THREAD

**Issue by raucao** [railscamp/railscamp-germany-2013#18]
We need a reception stand, and we need to put up a schedule where people can put their names in for operating it for an hour each.

**Comment by p886** [comment]
I would like to help with that.

**Comment by jhilden** [comment]
Very cool.  We are very glad for any help.

These are the task I see from my perspective:
- [ ] talk to people about volunteering to sit at the reception
- [ ] create a schedule
- [ ] create a participants list for receptionists to check off, after tickets are sold
- [ ] make sure we have all the necessary stuff we need

**Comment by raucao** [comment]
I don't think talking to people about sitting there makes a lot of sense. Just create a list and let people enter their names. Then we can fill it by asking people via Twitter and email.

The schedule should just be full hours, so it's easy to remember. We mainly need to decide how long it should be manned.

The participants list is there on Eventbrite automatically. They have tools for all these things.

What I'm missing is: setting up the stand itself or at least making sure it gets set up. ;)

**Comment by p886** [comment]
I reckon a Google Spreadsheet [like this](http://bit.ly/13ViiEi) would work ok? Anyone who has the link can pick a date and enter his / her name.

When should the reception be open?

**Comment by p886** [comment]
Below you'll find an email correspondence between @jhilden and me. I think it's a good idea to allow registration on Friday. What do y'all think? I can be at the site at around 6pm on Friday.

```
Hi Jakob,

ich hab noch ein paar Fragen zur Rezeptions-Organisation:

- Wann soll die Rezeption geöffnet haben? Auch shcon am Freitag? Ab wieviel Uhr?
- Kriege ich dann von euch die Liste mit den Teilnehmer, sodass wir an diese an der Rezeption abhaken können?

Wäre super, wenn du mir kurz Auskunft erteilen könntest.

Besten Dank und bis Freitag!
```

```
Hallo Philipp,

anbei ein Beispiel wie die Liste aussehen wird.  Machen wir dann denke ich nochmal ne frische.

Ob wir schon Freitag Rezeption & Registration machen sollen weiss ich gar nicht.  Macht vielleicht schon Sinn, dann hat man Samstag weniger zu tun.

Kannst du das hier in jedem Fall nochmal auf GitHub posten, damit das öffentlich ist?  Danke.  Ich werd dann dort auch nochmal antworten

Gruß, --Jakob
```

**Comment by erdnusskeks** [comment]
I will be there at about 5 / 5.30 pm and I can also help at the reception. And I bring the Namensschilder with me. : )
