### ISSUE TITLE
Lanyards / Passes

### ISSUE THREAD

**Issue by raucao** [railscamp/railscamp-germany-2013#19]
We need to create conference passes (no need to print names, we can just let people fill them in on the spot). We also need lanyards. We have tons in the office, but it should probably be a lanyard sponsor who pays for more than just the lanyards, because it's extremely visible advertising.
- [ ] Design and print passes
- [ ] Get plastic jackets for the passes
- [ ] Get lanyards

**Comment by jhilden** [comment]
Do we really need them?  Can't we just use Kreppband + Edding for names?   I personally find them stupid and unecologic.  Unless we really need a Lanyrd sponsor, I would vote for not having them.

**Comment by raucao** [comment]
Does anyone know where we can get something like these? http://www.guidedproducts.com/green-eco-friendly-name-badge-holder

**Comment by raucao** [comment]
https://twitter.com/janl/status/346189439606878208
https://twitter.com/janl/status/346190138646343680

**Comment by DonSchado** [comment]
"The Railsgirls" want to order cool lanyards. (via @lliane)

**Comment by raucao** [comment]
@lliane Cardboard with cotton ribbons?

In any case: we need a design where people can write down their names and Twitter handles themselves. Also: both sides printed.

**Comment by erdnusskeks** [comment]
![namensschilder](https://f.cloud.github.com/assets/4786471/758572/f6757a0a-e73e-11e2-87c0-4ca866fb9103.JPG)
Have a look at these drafts. They are made of (packaging) paper, cardboard and tape. You can print out the names (plus twitter name and maybe the rails camp logo) and stick the printouts on cardboard or just fold them two times (A4 => A6 = perfect size!). It's also possible to write the name on it by yourself (in that case we also need some markers). I tried to use as much used material as possible - old packaging, papers etc. I really like the tape! It looks quite special and simple at one time. And it is not that expensive (7,49 € per roll [50mm x 66m], Amazon). But the white-and-red-tape works much better on brown (or at least non-white) paper. I asked a colleague about shoelaces as ribbons for the badges. Otherwise I would look for low priced strings (Amazon or Bauhaus). I already showed some of the badge drafts to Liane, Tatjana and Anna. You can use these drafts as a basis. Improving is fine! Just tell me what you think about them. Which draft do you like the most? Or don't you like them at all?

**Comment by jhilden** [comment]
Thanks @erdnusskeks. I think the red and white tape will look really nice together with the Railscamp logo.  I would vote for number 4.

**Comment by raucao** [comment]
Nice work!

I'm not sure I understand exactly how these were made, but I like 1 and 4 best. Where would we print the logo and event name, though? Would that look good in combination with the big red stripes?

**Comment by jhilden** [comment]
What's the current state/plan/budget here?

**Comment by erdnusskeks** [comment]
Sorry, sorry. I waited for stuff I ordered. Now it arrived and I started to prepare everything. By the way: number 4 is the winner (with two votes)! ; ) 

I will cut the packaging paper (DIN A 4) and fold it two times so we have 4 paper layers (much more solid than just one layer). Then fixing everything with tape, stabbing a small hole for the lanyards/ribbons - and everyone can write his/her name on the badge. I guess this is the best way to put the names on the badges. So we can prepare everything now and don't have to wait for all the participants' names and we don't need a printer. We just need some markers - could anyone buy a bunch of black eddings? Staples is near Handelshof - @schorsch ?! can you jump over there to get them? And can someone send me logo and event title like you put it on the website? 

![image](https://f.cloud.github.com/assets/4786471/815203/fb70e944-ef23-11e2-9a84-6c3cf2e7a62e.png)

Just the flame and the lettering "RailsCamp Germany 2013". 
I want to order a stamp so it will be easy to put logo and name on the badges. And if everything works fine I already have some girls who will help me. : )

Unfortunately, the plan with the shoelaces won't work. So I have to improvise. ; ) Any ideas? Always welcome!  

Did I forget anything? I hope you will like the results. At least it's unique and cheap. ; )

**Comment by jhilden** [comment]
I think it's going to be the best lanyards ever!

I especially like the idea with the stamp :thumbsup: 
Here is an Adobe Illustrator file of the flame:  http://dl.5apps.com/stuff/flame.ai   And here is a low-res image with the lettering: http://screencloud.net/v/wSWi  Not sure if that's enough.  I think it would be a good idea to leave out the "2013", so we could also use it for future Railscamps.

**Comment by erdnusskeks** [comment]
Hm, the lettering is quite small (34 KB). Is there any chance to get it in a higher definition? Maybe even the .ai version? "Worst" case would be a stamp with just the flame. ; )

**Comment by raucao** [comment]
It's just HTML and CSS on the website. No graphics.

You should just use the font, which is the free Source Sans Pro in its 300 cut: http://sourceforge.net/projects/sourcesans.adobe/files/

**Comment by erdnusskeks** [comment]
Ok, thanks. But I can't make it with Word. It's too mühsam... I don't have any other programme on this computer and time is not on my side... So I will just go to the printshop and ask if they can make it with the small lettering. Maybe it works! : )

**Comment by lliane** [comment]
Ask me!
How can I help? Skype mich an!

Am 18.07.2013 um 10:22 schrieb erdnusskeks notifications@github.com:

**Comment by raucao** [comment]
\o/

**Comment by erdnusskeks** [comment]
111 Namensschilder - yay! @tatjanala works on 20 more. Got so much support from the SWOYP ladies and Anna G. - really really great! 

![111_namensschilder](https://f.cloud.github.com/assets/4786471/851686/de8ef2d0-f4a0-11e2-96d3-baecb0e842ef.jpg)

**Comment by erdnusskeks** [comment]
Not to forget: the stamp design by lovely @lliane ! : )

**Comment by raucao** [comment]
Splendid!

**Comment by bumi** [comment]
whoa! best namensschilder ever! :heart_eyes:

**Comment by DonSchado** [comment]
Amazing! :)
