### ISSUE TITLE
TV/monitor screens

### ISSUE THREAD

**Issue by raucao** [railscamp/railscamp-germany-2013#20]
We need some big-ass screens for Twitter wall, schedule, etc.. Maybe we can borrow them from some friendly companies?

**Comment by Uepsilon** [comment]
Remember that you'll also need some device to run the screens (obviously). :smile:  I'd recommend PIs. I have some but we may need them for a project. Otherwise I can help out with at least 1. 

Even so i'd try to get some from the community for the event. At iacologne we had some from visitors.
