### ISSUE TITLE
Foosball tables ("Kicker")

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#21]
Maybe we can just borrow tables from some local agencies:  @railslove, HomeOffice Cologne, @adcloud, ???

Then we would just need to take care of transportation.

Anybody want to take care of that?

**Comment by jhilden** [comment]
Maybe some of our kicker pros want to take care of that?  @stephanpavlovic @tmschndr

**Comment by tmschndr** [comment]
If our table survives #iacologne's hardware hack track we can of course use them during Rails Camp. And _if_ it survives it will be pimped with sensors and stuff also – nrrdy.

**Comment by code-later** [comment]
As I already suggested we should consider renting two tables for the weekend. I contacted adcloud regarding this issue because they always rent a foosball table for events. I also searched the web (very briefly) to get a feeling what this would cost us. I came up with something between 200 and 400 Euros for two tables on two days. This doesn't include delivery. And a deposit would be needed too.

Does this sound feasible?

**Comment by raucao** [comment]
> Does this sound feasible?

I guess so. We'll have more sponsorship than we thought, so I'm fairly sure there's some money left for this. Let's wait until we know that for sure, though.

**Comment by code-later** [comment]
Agreed, I will just make some contacts to get the final prices. As soon as I know them I let you know. I guess/hope we can rent those stuff on very short notice.

**Comment by code-later** [comment]
I just got some very good news regarding the foosball tables:
- Each table would cost us 90 Euros for three days. They would be delivered on Friday and picked up on Monday
- We need to pay 50 Euros for delivery and pickup each

Overall this would be 280 Euros for two tables. It is possible to book this 1 week before the event starts.

The price is without tax.

**Comment by raucao** [comment]
\o/ Perfect!

**Comment by DonSchado** [comment]
@railsbros-dirk bestellt? :)

**Comment by code-later** [comment]
Foosball table is ordered and will be delivered at friday.

**Comment by raucao** [comment]
BRING IT ON!

**Comment by code-later** [comment]
I forward the invoice to Ruby e.V. right?

**Comment by raucao** [comment]
Yup.

**Comment by jhilden** [comment]
Closing this as it seems that everything is organized here.

**Comment by RmMsr** [comment]
@railsbros-dirk Wer war den der Anbieter der zwei Kicker über das WE für 280 vermietet? Ich suche für einen Sponsor 2 brandbare Kicker.

**Comment by code-later** [comment]
@RmMsr Das war [meinkicker.com](http://meinkicker.com). Kontakt war der Elias Schmoz (eliasschmoz@gmail.com).
