### ISSUE TITLE
T-Shirts?

### ISSUE THREAD

**Issue by moonglum** [railscamp/railscamp-germany-2013#22]
Do we want to offer T-Shirts? I always like to come back from a conference/... with a T-Shirt personally. There are basically three options in my opinion:
- The Ticket includes a T-Shirt (would require a price raise)
- You can add a T-Shirt at ticket-checkout optionally
- We don't offer T-Shirts :wink: 

I personally prefer option 2. But we would need a design then. But it wouldn't add any cost, because we would just sell the T-Shirts at the price it will cost us. But by forcing people to order them beforehand, we wouldn't produce to many T-Shirts that nobody wants :wink:

**Comment by raucao** [comment]
The problem is that a proper print (not digital, because that sucks and the shirts are done after a couple times washing) requires sifters to be produced and a bit of work to prepare the graphics for those. As that is upfront cost, the price of the shirts would vary, depending on how many we produce.

So, if t-shirts, I vote for producing proper quality, which means option 1 (or 3).

**Comment by moonglum** [comment]
I didn't think about that. You're absolutely right.

**Comment by raucao** [comment]
Option 4 would be to have a shirt sponsor, of course, but I would only vote for it, if it's done as tastefully as possible. The Advance Hackathon shirts from last year are a good example of how that can be done, though. Maybe we could even get AdCloud to sponsor that again.

**Comment by a2800276** [comment]
T-Shirts are stupid, if we have to much money, we should donate it to charity (or invest it in better food, more beer). If people want T-Shirts we can certainly offer a "premium" ticket that's €10 more expensive and make some TShirts.

**Comment by raucao** [comment]
Option 5 would be printing some (for mx half the number of participants) and then just selling them. Lots of confs do that for e.g. hoodies. We could also attach some charity donation to the ones sold on site. Maybe for the Travis Foundation or sth.

**Comment by jhilden** [comment]
+1 for quality t-shirts with a nice design
+1 for finding a T-Shirt sponsor

@skddc can you give us a rough number what it would cost for 200 t-shirts, so we can ask sponsors about it?

**Comment by raucao** [comment]
About 1000 bucks I guess. Our last order for my company was 7-color sifter print, which is just crazy. I think that was 1400 for 120 shirts, including everything. But we should ask again. If it's a single color or 2 max, it'll be cheap enough.

**Comment by Uepsilon** [comment]
I just thought, that if we'd like to have shirts, we should agree on the Design rather quick now (even if they won't be sold along with the tickets anymore). 

Shall we print the current Logo on those shirts? Or would it be better to print something else. In my mind i thought of a Rail (with some Rubys on it or so) which leads through a tent (on a clearance, if we can add the details), with the slogan "RailsCamp" beneath (which may reduce the daily-usage of the shirt). I guess that would have a greater impact than the current logo (which - no offense - is not the nicest one. Maybe we can replace it if the design is good). 

I can try to get a sample of what i'm thinking off but i'm rather bad at drawing. I can ask a friend if there is a general interest.

Regarding the Funding of those shirts: 
I think it's better to either accept preorders for shirts via the page (saying that they will be produced once a certain limit is reached - kickstarter-style) and then have some extra if someone decides to get one spontaneously.

Or we need a sponsor but that may lead to ads on the shirt which can repel some buyers (and definitely reduce the daily wearability).

**Comment by tandibar** [comment]
For good Quality T-Shirts I can recommend mcs in Berlin (http://www.multicolorshirt.de/) They have good quality and good prices.

**Comment by DonSchado** [comment]
will investigate with @lliane

**Comment by raucao** [comment]
\o/

**Comment by DonSchado** [comment]
to be honest, I would love to see/accomplish a very minimalistic design.
Also I dont't care about "tour dates", what about you? ;)
below a short sketch what I think:

Front Version 1
![front_0](https://f.cloud.github.com/assets/685742/742458/cbb34ff8-e3ca-11e2-9105-aca14a520c58.png)

Front Version 2
![front_1](https://f.cloud.github.com/assets/685742/742459/cbd0c16e-e3ca-11e2-936b-3618dba96a60.png)

Back, just for sponsoring? 
![back](https://f.cloud.github.com/assets/685742/742460/cbf03620-e3ca-11e2-948a-b3c99eb5cbf0.png)

**Comment by lliane** [comment]
<3 Version 1

**Comment by raucao** [comment]
Maybe we can put RailsCamp Germany on the sleeve, like on the EuRuKo Berlin shirts?

**Comment by DonSchado** [comment]
left/right side?
![sleeve](https://f.cloud.github.com/assets/685742/742574/2e3fa574-e3ce-11e2-87aa-93ed7152b6dc.png)

**Comment by Uepsilon** [comment]
I'm not to fond of the Logo. I'd like a minimalistic design too, but the logo does not suit my expectations. But I guess this is settle and cannot be changed right? :D

Furthermore I favor V-Necks over regular Tees, but I might be the only one. Is there any possibility to get the Shirts in both Ways or will that increase costs drastically?

**Comment by moonglum** [comment]
Voting for V1 :+1:

**Comment by raucao** [comment]
> But I guess this is settle and cannot be changed right?

Nothing is settled until they go into print. ;)

There's a design with the original Railscamp logo and the Kölner Dom somewhere. Can't remember exactly.

I think the type on the sleeve would look much better if it were way smaller and used Source Sans Pro, like the website.

**Comment by raucao** [comment]
Oops, hit the wrong button. :/

**Comment by jhilden** [comment]
Here is the design by @slogmen that @skddc was talkin about:

![railscamp_koeln](https://f.cloud.github.com/assets/69657/743107/520b7df4-e3e0-11e2-8496-b92c170af4ab.png)

**Comment by Uepsilon** [comment]
I like that one way more than the other ;) I'd really like to see that on a shirt.

**Comment by DonSchado** [comment]
I like both logos. :) 
but I think logo 1 is "brighter" on a black shirt... (which was the favorited color by @moonglum ;))

anyhow, Version 2 transparant
![front_2](https://f.cloud.github.com/assets/685742/743341/bd5c638e-e3e5-11e2-95a2-a03c349bb1c3.png)

Version 2 white
![front_3](https://f.cloud.github.com/assets/685742/743342/bdb1e188-e3e5-11e2-925e-4ca94a60f0fc.png)

any chance to get the raw psd/eps file? 

@skddc the font comes through the sketching with the Spreadshirt generator ;)

**Comment by raucao** [comment]
Why not use a grey or beige shirt for this one?

**Comment by DonSchado** [comment]
hmmm....

![gray1](https://f.cloud.github.com/assets/685742/743424/a6e9b7da-e3e7-11e2-986a-ef0100cb1c9e.png)
![gray2](https://f.cloud.github.com/assets/685742/743426/a72388fc-e3e7-11e2-8ecf-6b3f00482273.png)
![sand1](https://f.cloud.github.com/assets/685742/743425/a709a0e0-e3e7-11e2-943c-dd6ebd8024d2.png)
![sand2](https://f.cloud.github.com/assets/685742/743427/a729f020-e3e7-11e2-9da3-558f1038b5b5.png)
![blue1](https://f.cloud.github.com/assets/685742/743429/a787f2d8-e3e7-11e2-9950-7e85ece07bdf.png)
![blue2](https://f.cloud.github.com/assets/685742/743428/a7346c94-e3e7-11e2-86cb-7fa9c53d41b2.png)

**Comment by endverbraucher** [comment]
Looks great! Raw SVG/EPS available here: https://www.dropbox.com/s/erabkbguwvohiio/railscamp_shirt.zip

**Comment by raucao** [comment]
That's dark grey and okker. ;)

Hint: if you're just using Spreadshirt colors, you won't find good ones anyway. Another nice one would be whatever it was the Advance Hackathon shirts are made of (very dark grey, almost black even, with some organic pattern). Everybody just loves the color, material and cut, aside from the cool graphics. @lliane You know what these are, right?

**Comment by lliane** [comment]
Yes. It was American Apparel, grau meliert! But they were quite expensive (about 35 Euros each). http://www.spreadshirt.de/maenner-slim-fit-t-shirt-C7196G1P24T84 > Männer T-Shirt Tri-Blend von American Apparel
(Find it via the slider)

**Comment by Uepsilon** [comment]
Spreadshirt is quite expensive (not to mention delivery costs and duration) and the quality is quite poor. I guess they use the page only for the Preview. 

I guess the Logo must be emphasized on a dark background (or on a blue one), maybe place it in a shaded area which may be ruby-shaped (or shaped like the railscamp ger logo?)

**Comment by lliane** [comment]
Spreadshirt was just where we ordered the Advance Hackathon T-Shirts! The quality was perfect.

**Comment by Uepsilon** [comment]
okay, maybe it depends on which type you choose. I've ordered there twice, both times different types (dunno which ones) and the white ones where nearly see-through and the black one where washed out after 2 or 3 times. Not expecting much. But maybe it was just my luck ;) 

Nonetheless, I'd rather sink my money for a shirt from a local printshop than for one from another country.

**Comment by raucao** [comment]
"American Apparel, grau meliert" is all we need to know. If we print properly, we'll have to provide the shirts anyway, or let the printer order for us from a catalog. No need to use Spreadshirt just to get those exact shirts.

**Comment by moonglum** [comment]
@DonSchado This moonglum guy has an awesome taste. Really like Version 2 white.

**Comment by DonSchado** [comment]
After some investigation with Liane, maybe "American Apparel, grau meliert" is actually wrong. ;) The color from the Advanced Hackathon is darker and maybe it's "schwarz meliert". A Coworker says the right name is "american apparel tri black". :)

![shirt-color](https://f.cloud.github.com/assets/685742/749575/e1f38842-e4af-11e2-82f3-a69057f3bd1a.png)

But, more important is the logo. 
What about something like this?
![yield](https://f.cloud.github.com/assets/685742/749625/31f78932-e4b1-11e2-9bd3-76753253cfcf.png)
![yield-2](https://f.cloud.github.com/assets/685742/749659/1bf6e3a2-e4b2-11e2-9953-32d3062f133e.png)

![shirt-yield](https://f.cloud.github.com/assets/685742/749626/3690e128-e4b1-11e2-8071-6efad2cbed9f.png)

maybe @lliane is in the mood to scribble something cool? :) I'm not that good with color harmony ;)

**Comment by raucao** [comment]
I liked the one with just the blue lines actually. Also cheaper to print with sifters if it's only one color.

**Comment by Uepsilon** [comment]
@skddc I think the one with plain blue lines is kinda hard to read, but maybe that's just the preview. 

I like the one with the white filling and the diamond-shaped background. But i'm not quite sure about the background color (i've played a little bit with different colors but it does not look right).. even if i wouldn't take a light blue but a light gray or so instead. 

The round background reminds me of the PHP-Logo, which should be a NoGo ;)

Maybe 2 Types of shirts, one with filling one without and no background?

**Comment by raucao** [comment]
Here's a vector version of the flame: http://dl.5apps.com/stuff/flame.ai

**Comment by DonSchado** [comment]
Sooo erste Antwort von X-Print (aus Köln), die haben gesagt, das bekommen die zeitlich hin.

"pro Druck müssen Sie bei weißen Shirts und einer Auflage von 160 Stk. mit folgenden Preisen rechnen:
1,37 € / pro einfarbigen Druck
1,64 € / pro einfarbigen Druck wenn auf Ärmel gedruckt werden soll."

Für American Apparel, Tri-Blend Black, schickt er mir morgen das Angebot. 
Wenn man mal mit 20€ kalkuliert, wären wir bei ~3500€. 

Gedacht hab ich an 80Stk. mit der Flame und 80Stk. mit dem Dom. 
Fehlen nur noch die Größen.

**Comment by raucao** [comment]
Das sind glaub ich zuviele. Lass dir mal vorsichtshalber ne Hausnummer für die Hälfte davon geben würd ich sagen.

**Comment by raucao** [comment]
Wenn das Siebdruck ist, dann ist es deutlich teurer 2 verschiedene Motive zu machen. Eins reicht auch finde ich. Wir sind ja kein Klamottenladen.

**Comment by jhilden** [comment]
Thanks a lot for getting those prices for us. Really great.

This was siebdruck, yes?
I agree that asking for a qoute for 80 pcs won't hurt and i would also say
one design is enough. I like both.

**Comment by moonglum** [comment]
One design is enough, I totally agree :wink:

**Comment by DonSchado** [comment]
"Hallo Herr Schaden,
das T-shirt kostet blanko 11 Euro netto zzgl. Mwst. Wir müssten uns jedoch beeilen, da die Shirts direkt aus LA versendet werden und der Versand ca. 5-7 Tage dauert.
Gruß Nino Boender"

**Comment by Uepsilon** [comment]
Gibts keinen Laden in Deutschland oder wenigstens Europa wo man die Shirts kaufen könnte? Muss man die aus LA bestellen? Ich persönlich find es auch schöner ein Design zu machen. Ich, als Kölner, bin natürlich für den Dom ;)

**Comment by jhilden** [comment]
Ich würde sagen wir schicken heute abend oder spätestens morgen den Survey
raus, warten dann bis Montag auf Antworten, und bestellen dann mit ein
bisschen Polster irgendwie so 60-120 T-Shirts (je nach Interessenslage).
 Für die Nachzügler muss man dann nochmal guckn, notfalls besorgen wir
kurzfristig lokal noch T-Shirts.  Ich gehe mal davon aus, dass der Druck in
der letzen Woche vor dem Camp stattfinden wird.

Würden mit 15€ pro T-Shirt auf jeden Fall alle gedeckt sein (auch bei
kleinerer Auflage)?   10€ T-Shirt + 1,90€ MwSt + Druck ~1,30-2€.  Oder hab
ich noch was vergessen?

2013/7/10 Uepsilon notifications@github.com

**Comment by DonSchado** [comment]
So wird's bestellt, wenn bestellt wird.
Restliche Einzelheiten versuche ich mit der Druckerei heute noch zu klären.
Lasse mir jetzt ein Angebot für 100stk machen.

![railscamp-shirt](https://f.cloud.github.com/assets/685742/780270/260e1e54-e9fe-11e2-82ac-de0892769873.jpg)

**Comment by moonglum** [comment]
@DonSchado Finde ich super. Will ich haben.

**Comment by Uepsilon** [comment]
@moonglum Dito ;)

**Comment by DonSchado** [comment]
Hier die neuen Preise für 100 Shirts:
- T-Shirt 11 Euro netto zzgl. Mwst (13,09 € brutto)
- Logo zweifarbig auf dunkle Textilien 3,81 € brutto inkl. MwSt.
- Ärmeldruck Schriftzug kostet 2,80 Euro inkl. MwSt.

Wäre ein Gesamtpreis von 19,70€, oder glatt 20€. 
Nur Logo fände ich auch ok, dann könnten wir das Shirt für 17€ anbieten.

**Comment by raucao** [comment]
Nur Logo fänd ich auch gut bei diesem Motiv. Super!

**Comment by tandibar** [comment]
Mir kommen die 11 EUR po Shirt recht teuer vor. Wenn das zeitlich noch möglich ist würde ich vorschlagen, dass wir noch ein Angebot von MCS einholen ((http://www.multicolorshirt.de/). Habe sehr gute Erfahrungen mit denen gemacht und die sollten das Angebot preislich unterbieten können.

**Comment by jhilden** [comment]
@thyphoon wenn du uns bis morgen ein konkretes Angebot von den besorgen kannst was besser ist und auch zeitlich noch funktioniert, dann können wir auf jeden Fall drüber reden.   Ansonsten finde ich es gut nen lokalen Anbieter zu haben, weil es ja evtl. wirklich zeitlich knapp werden könnte.

**Comment by raucao** [comment]
Der Druck ist ok. Der Gesamtpreis kommt zum großen Teil, wie man ja auch sieht, aus den hochwertigen Shirts. Billigshirts kosten so 1-3 Euro, aber diese haben einfach tolles Material und Schnitt. Je höher die Auflage, desto günstiger wird der Druck dann. Siebe und Datei vorbereiten ist nämlich Grundinvestition, egal wie viele Shirts man druckt.

**Comment by moonglum** [comment]
Ärmeldruck oder nicht: Hm – ich tendiere zu keinem Ärmeldruck ;) Guckt eh kein Mensch drauf. 17 bzw. 20 Euro finde ich super.

**Comment by Uepsilon** [comment]
Sind in den 11€ zum Shirt schon die Shippingkosten für die Shirts mit drinne? Klang irgendwie nicht so.

Ich frag mich gerade, ob man nicht auch andere Kragenformen anbieten sollte. Ich finde rund zB nicht so cool (auch wenn es irgendwie 99% tragen). Wenn man eh shirts + druck einzeln macht, könnte man doch einfach 20 graue shirts (rund), 20 schwarze shirts (rund), 20 rote shirts (rund), 5 graue shirts (vneck), 5 schwarze shirts (vneck), 5 rote shirts (vneck) holen und diese immer gleich bedrucken lassen ohne das sich die kosten dafür ändern oder? 

Fänd ich besser und kommt auch bestimmt besser an. Oder überseh ich was?

**Comment by DonSchado** [comment]
also ich würd ja sagen so kurzfristig, sollten wir da jetzt nicht noch x-mal das Angebot ändern. 
Zudem ändern sich dann auch wieder die Preise je Shirt etc... 
und wie Basti schon sagte: "Wir sind ja kein Klamottenladen". ;)

11€ netto war im Angebot, also vermutlich incl. Shipping, da das über den Drucker abgewickelt wird.
Find das ist schon sehr fair.

**Comment by raucao** [comment]
Keep it simple, please.

**Comment by Uepsilon** [comment]
Typisch Deutsch Over-engineered :D Recht hat er ;)

**Comment by moonglum** [comment]
Ja, stimme @skddc absolut zu – bloß nicht :wink: Eine Farbe, ein Schnitt, ein Logo. Fertig.

**Comment by lliane** [comment]
Raus damit! Ich find's sehr cool!

(( Und einen Kommentar zu V-Necks muss ich mir jetzt richtig dolle verkneifen :sunglasses: ))

**Comment by moonglum** [comment]
Wann geht denn die Umfrage zu den T-Shirt Größen raus? Oder habe ich was verpasst?

**Comment by tandibar** [comment]
Ok, MCS hat kein American Apparel im Angebot, wenn es also genau das Shirt sein soll sind die raus. Verfolge das Thema also nicht weiter und wir nehmen das aktuelle Angebot.

**Comment by DonSchado** [comment]
@jhilden und ich haben ein paar Zahlen geschubst und sind jetzt mit kleinem Puffer bei 75 Shirts:
8S + 22M + 30L + 12XL + 3XXL

Das wäre jetzt das was ich heute zwischen 11 und 11:30 bestelle!
Sofern der Typ noch bock auf uns hat, nach der dritten Mengenänderung. ;-D

**Comment by raucao** [comment]
Also keine Vorbestellungen erst?

**Comment by DonSchado** [comment]
Was meinst du? :)

**Comment by raucao** [comment]
Egal, hab grad das Survey-Update gesehen. ;)

**Comment by jhilden** [comment]
@skddc Wir haben die Daten aus dem Survey ein bisschen extrapoliert und damit entschieden wie viel wir bestellen wollen.  Wir **müssen** heute bestellen sonst wird das nix mehr zeitlich.

Hier sind die Daten:

Wir haben 40 Responses erhalten und davon wollten 62.5% ein t-shirt kaufen.  Hier die Details:

```
S           2   
M          8
L           10    
XL         4
Bigger    1
```

Wenn wirklich 62.5% ein t-shirt nehmen, dann sollten wir mit den 75 bestellten shirts genug haben für 120 Teilnehmer insgesamt haben.

**Comment by raucao** [comment]
Weiß nicht wie du auf 120 kommst, nachdem wir 90% der ersten Charge los sind, aber gut. Lieber zu wenige als zu viele!

**Comment by DonSchado** [comment]
Antwort vom T-Shirt Mann: "Lieferung würde so wie es aussieht klappen"

**Comment by raucao** [comment]
\o/

**Comment by jhilden** [comment]
Warum "würde"?  Ist das noch nicht final?

**Comment by DonSchado** [comment]
Doch alles gut! :)
War jetzt aus dem Zusammenhang gerissen.

**Comment by DonSchado** [comment]
"die shirts sind heute angekommen und werden donnerstag gedruckt"

**Comment by moonglum** [comment]
@DonSchado You're awesome :dancers:

**Comment by raucao** [comment]
They're beautiful!
