### ISSUE TITLE
Main stage

### ISSUE THREAD

**Issue by raucao** [railscamp/railscamp-germany-2013#23]
We need some kind of elevated stage in the main hall (not much, but higher than ground level), as well as a large screen and proper projector. Also: stand for laptop with video and audio connection to projector and sound system. With these dimensions it's impossible to mcgyver that on the spot, because the cables alone are a problem we have to solve upfront.

**Comment by thilo** [comment]
Do we have a Soundsystem and Beamer already or do we need to rent that?

**Comment by raucao** [comment]
There's #3 for that I think.

**Comment by jhilden** [comment]
They have enough stage elements there, so we can build whatever kind of stage we want to.  They also have a technician there who will propably do most of the upfront work.  But he won't be there during the event.

**Comment by raucao** [comment]
Wow, great! This venue is getting better and better. :)
