### ISSUE TITLE
German or English?

### ISSUE THREAD

**Issue by moonglum** [railscamp/railscamp-germany-2013#24]
Will the sessions be in German or English? Will it be mixed? Whatever we do, we should inform people beforehand. This is really important.

**Comment by moonglum** [comment]
I'm currently at a conference in the Ukraine. Website is available in English and everything. But with the exception of five talks (which are all given by people from outside the Ukraine), all talks are in russian or ukrainian. There was no information about this beforehand.
(We we're invited to speak here, so no harm done, but still...)

**Comment by thegcat** [comment]
As it's Railscamp Germany I'd say preferably German, without closing the door to English talks, but as you said with proper tagging of English talks.

**Comment by moonglum** [comment]
Not sure... RuPy in Hungary and RailsBerry in Poland are also English-only.
Or is it different for a Camp and a Conference?

**Comment by klaustopher** [comment]
I'd also vote for German :de:

**Comment by a2800276** [comment]
Dann brauchen wir aber auch nicht auf English zu planing, or?

**Comment by raucao** [comment]
We're open to everybody, and especially in the last 2, 3 years a huge wave of international devs arrived in Germany, working here full-time now, but maybe not being proficient enough to understand or speak in German (in our company we have a 1:2 ratio of non-Germans to Germans). I also wanted to invite our Polish friends who weren't able to attend Railsberry. We should be open to everyone, regardless of language, so I'd say preferred language is English, but I'd encourage people to do talks in German, if they're not comfortable enough with doing it in English!

I, too, think it's a good idea to mark the session language beforehand, and probably tell people that it'll be mixed languages. Whatever we do, we can always react to the situation during the event, and also beforehand, when we see who's buying tickets.

Keeping the planning in English ensures the same kind of openness and transparency, and don't forget we're looking for all participants to contribute!

**Comment by a2800276** [comment]
Also, it's supposed to be a barcamp, right? So we should be able to respond spontaneously. If someone wants to do a talk in German and noone wants to hear it / vice versa ... 

In general, we can announce that:

```
  "for the benefit of non-German speaker, talks should ideally be held 
 in English (it's the new Latin). BUT LEARN THE FUCKING LANGUAGE 
 IF YOU WANT TO  LIVE HERE YOU STUPID LAZY AMERICAN 
 BERLIN-IS-JUST-AS-COOL-AS-BROOKLYN SLACKERS! That said, anyone 
 is free to speak in the language they feel most comfortable in if they find an 
 audience. We expect the majority of the talks to be in English, albeit with 
 terrible tee hätsch mispronunciations, so if you don't understand English at 
 all, you may not get your money's worth."
```

**Comment by raucao** [comment]
I'll try to rephrase that in a more agreeable way and publish it. ;)

**Comment by a2800276** [comment]
... and I was trying so hard to be diplomatic!

**Comment by jhilden** [comment]
Closing this issue:  **default language should be English, but German talks are just as welcome (they should be marked in the schedule)**

I also think that each speaker / session organizer can simply ask for each session if there are any non-German speakers in the room.
