### ISSUE TITLE
DNS, Email, Domain

### ISSUE THREAD

**Issue by raucao** [railscamp/railscamp-germany-2013#25]
We need an email address for sponsors to reach us. I just gave away mine on Twitter, but ideally we have sponsors@railscamp.de.

I already asked Mario Schröder, the one who coorganized the very first RCG with us and is owner of the domain, if he can change the nameservers to something every current team can then administer. We should also route 2013.railscamp.de to the GitHub page for example.

Hope I get some contact soon, he didn't respond so far. :(

**Comment by jhilden** [comment]
Vielleicht sonst erstmal noch eine andere alternative Domain registrieren, damit man schon mal was hat?

Die sind noch frei:

```
railscamp.co    
railscamp.net   
railscamp.org   
railscamp.info
railscamp.eu
```

**Comment by raucao** [comment]
Mario just sent me an email with the auth code. Transfer is in progress. Will set up email and `2013.railscamp.de`.

**Comment by raucao** [comment]
Ok, domain is set up: http://2013.railscamp.de (might not work in FF until restart)

Email is accessible at https://webmail.gandi.net (user mail@railscamp.de – ask me directly for the password). Messages should be forwarded to the Google list.
