### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by raucao** [railscamp/railscamp-germany-2013#26]
Tracking issue for the website.

I started working on it today and pushed my stuff to a branch. @slogmen wants to help as well from here on.

If anybody wants to have a look, make sure to open it in Chrome for now, and that you have Source Sans Pro installed on your system. Then just check out the branch and run `jekyll serve`.

If you want to make continuous changes, add a `--watch` to that command.

Would be cool if somebody could set up Sass somehow. Maybe with http://matthodan.com/2012/11/22/jekyll-asset-pipeline.html or something.

And if you want to catch us directly, our XMPP handles are basti@xmpp.kip.pe and slogmen@jabber.ccc.de

**Comment by raucao** [comment]
I added https://github.com/noct/jekyll-sass for now and cleaned up the CSS a bit. Also added a Gemfile, so you can just use Bundler from now on in order to get the plugins etc.

**Comment by jhilden** [comment]
I will close this issue.  We can make new ones for small upcoming changes to the website
