### ISSUE TITLE
Beer garden

### ISSUE THREAD

**Issue by raucao** [railscamp/railscamp-germany-2013#27]
In order to be able to sit outside at night (esp. for the BBQ), I think we should set up a small beer garden again. So we need tables and benches. We might get them on the cheap from a brewery if we buy enough beer from them.

We can also use the stuff during the day to add seating and tables where necessary, be it the main hall, a small room, the skate hall, or the tent. And just have some outside during the day anyway, of course.

**Comment by jhilden** [comment]
The venue has ~40 "Biertischgarnituren" that we can rent for a cheap price (they want to sent me detailed prices next week).  So that should not be a problem.   They also have a couple of standing tables and maybe even something tent-like.  But I think we will need to rent a tent anyway.

**Comment by raucao** [comment]
\o/ That solves the whole issue. :)

**Comment by jhilden** [comment]
We should be able to get 10-15 Liegestühle from AddCloud.  We just shouldn't forget.

**Comment by jhilden** [comment]
@mobbit will check about the Liegestühle

**Comment by martinotten** [comment]
@jhilden looks like the chairs are needed at another event :(

**Comment by raucao** [comment]
Which chairs?

**Comment by jhilden** [comment]
Oh noes.  Where can get some Liegestühle now?  Anybody any ideas?

**Comment by raucao** [comment]
Erento or sth?

**Comment by jhilden** [comment]
They have Liegestühle available for the weekend in Wuppertal, but they don't have any free cars to deliver them.  http://www.barnane.net/liegestuehle.html  7€/chair

Is by chance anybody with a decent sized car coming through Wuppertal?

**Comment by raucao** [comment]
7 EUR for these crappy chairs? Sounds expensive.

Maybe we should check Baumarkt offers and just buy some.

**Comment by jhilden** [comment]
There is a Bauhaus and a Praktiker pretty close to the venue, but I wasn't able to find any Liegestuhl prices online.
