### ISSUE TITLE
Projectors (aka "Beamers")

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#28]
We need somebody to take care of projector setup.

This is what is available at the venue:
- 1x 2600 lumen projector  (which is reportedly a little weak for the main hall)
- 1x 6x4m screen
- 1x 3x2m screen

For the 4 small conference rooms we can probably just take regular projects that we can hopefully even borrow from local agencies.
- [ ] Main hall -> big rented projector
- [x] Skate hall -> ?  (i don't think there will be sessions in the skate hall)
- [x] Room "BigConf"  ->  Abenteuerhalle projector, no screen needed
- [x] Small room 1 -> CowoCo projector, no screen needed
- [x] Small room 2 -> Home Office Cologne projector
- [ ] Small room 3 -> small rented projector

Who wants to take care of this?

**Comment by jhilden** [comment]
@timoschilling did you ask your contact if we can get some projectors from them?

**Comment by bumi** [comment]
besides the small projectors that we can have from cowoco & co. I'd say we should get some that work in (bright) light. for the nodecamp.eu we've rented one from Projektor AG (Köln-Dellbrück)
one with 4500 ANSI-Lumen + 1024x768px resolution would there be 138€ for two days.

**Comment by timoschilling** [comment]
I will ask him on Monday

**Comment by jhilden** [comment]
@timoschilling any news?

I just did a quick Google search and came up with this http://www.projektorvermietung.com/preisliste.html they have a 5500 Lumen projector for something like 90€.

**Comment by timoschilling** [comment]
@jhilden @bumi news, but no good one, no projector available

**Comment by jhilden** [comment]
For the main hall we need a projector to project on a 4x3m screen from ca. 6m **fixed** distance.  We need to take this into account when ordering, so it has the right lense.

@railsbros-dirk said they can bring a small projector from Home Office Cologne, so we only need 2 more for the smaller rooms.  Who else could bring a projector?

**Comment by tatjanala** [comment]
Hey, I just talked to someone at  http://www.projektorvermietung.com/preisliste.html and we can have either an 5500 Lumen projector or an 4500 Lumen projector (which is almost as good as the other one cause it has new lamps an stuff) from friday 18h till sunday 18h for 75€ (for two days). If we need two more regular projectors as well it's not a problem. They cost around 30€ for two days...

**Comment by bumi** [comment]
from what I was researching... that's a good deal. with a price at around 20-30€ I would also say let's get an additional small one. (for example: Sanyo PLC-XU350a )

**Comment by jhilden** [comment]
agreed.  let's make it final.  let's get the big projector and 1 small one.

will they deliver the beamer to the venue, or do we need to get it?   it should ideally be there by friday noon, because we will need to fix it to the traverse in the venue.  does it/they have any sort of fixing-projector-to-traverse-stuff?

Anything else you need to know to finalize it @tatjanala ?

**Comment by tatjanala** [comment]
It's done. We'll get a Sanyo PLC-XP55 4500 ANSI and two regular projectors (2800 ANSI) for 140€. A 20 m HDMI cable is inclusive. Someone has to pick it up at 
Schmidt Dietmar 
Tenktererstr. 3
50679 Köln 
on Friday morning. 30€ are allready paid, but the one who picks it up has to pay 110€ + 300€ (deposit) in cash!

**Comment by jhilden** [comment]
At what time exactly can we pick up the projectors and who will do it?   Since we need to fix the big projector to the ceiling it would be good if it could be at the venue by noon.

**Comment by tatjanala** [comment]
Friday morning around 8 am or Thursday evening. Projector guy number: 0163/8477785. Remember to bring the money!

**Comment by jhilden** [comment]
FYI @tatjanala:  @DonSchado is coming to the venue now and can pick up the projectors between 12:00 and 12:30

**Comment by jhilden** [comment]
We have the projectors here.  However, we didn't get the ~20m DVI cable that we needed.  Anybody any idea where we could rent a cable until tomorrow, or buy one for a decent price?
