### ISSUE TITLE
Room plan

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#29]
We have the following rooms in the venue:
- A slighly bigger conference room for 20-30 ppl.
- 2 small rectangular conference rooms for 10-15 ppl.
- 1 small long conference room for 10 ppl
- the sports court in the main hall for the welcome & session planning 200+ ppl
- seating area around the bar (same room as the court, so we can't do extra sessions there, only maybe during basketball/soccer playing)
- skate hall (big hall with multiple corners that we could use, but only until 15:00 max)
- bbq, tent & beer garden area behind the halls
- area in front of the halls.

**Comment by raucao** [comment]
Sounds good!

**Comment by jhilden** [comment]
As any good Railscamp, of course we need codenames for the rooms with a cool theme.  We thought a pirrrate theme could be cool:
- "main deck"
- "quarter deck"
- "galley" / "kombüse"
- "gangway"
- "poop"
- "porthole"
  ...

Looking for more good names ...

**Comment by timbuchwaldt** [comment]
Is there a chance to get a (lockable) network room where we can set up the gear?

**Comment by jhilden** [comment]
Definitely.  I will explicitly look/ask for it the next time I'm at the venue

**Comment by kristin-s** [comment]
![basic ship plan](https://f.cloud.github.com/assets/5016015/811646/adfa3018-eedc-11e2-8375-6e7f214a5264.jpg)

**Comment by raucao** [comment]
@kristin-s Hah, awesome! :)

**Comment by kristin-s** [comment]
I think this might help you to decide on some good names for your camp... ;)
Have a look whether this works for you: 

"We have the following rooms in the venue:

```
A slighly bigger conference room for 20-30 ppl.   -->    Mate's Quarters
2 small rectangular conference rooms for 10-15 ppl.   ---> Great Cabbin I & 2
1 small long conference room for 10 ppl         -->  Sail Room 
the sports court in the main hall for the welcome & session planning 200+ ppl    -->   Navigation Room
seating area around the bar (same room as the court, so we can't do extra sessions there, only maybe during basketball/soccer playing)
skate hall (big hall with multiple corners that we could use, but only until 15:00 max)
bbq, tent & beer garden area behind the halls      --> Galley 
area in front of the halls."  --> sea bottom 
```

**Comment by kristin-s** [comment]
I have no idea why this looks like it does but at least it hopefully catches some attention :dart: 

Thanks Jan, btw I still try to convince Jakob that you all dress up as pirates
