### ISSUE TITLE
Audio, music & light equipment

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#3]
We need somebody to take care of audiovisual equipment, e.g.
- [x] make sure the music equipment the venue has fits our needs, or get something else
- [x] organize music or a DJ
- [x] possibly we need an PA system
- [x] maybe we need some extra lighting (e.g. outside)

@railsbros-dirk seems to have some experience in this area ;) 

Also maybe @putpat wants to sponsor this?

**Comment by raucao** [comment]
Let's split it up, so that more people can do less.

**Comment by moonglum** [comment]
Don't poke in the wound, there are no Galaxy Cats anymore :crying_cat_face:

**Comment by moonglum** [comment]
@klaustopher @EinLama Maybe you can harass your boss to get putpat music for the weekend?

**Comment by raucao** [comment]
Sound system sponsor maybe?

**Comment by moonglum** [comment]
Would be awesome :wink: Just sell it to your boss as "recruiting cost" :tongue:

**Comment by klaustopher** [comment]
Getting music won't be a problem ;) I'll ask about it

**Comment by moonglum** [comment]
:+1:

**Comment by upstream** [comment]
I can bring two wireless microphones from co.up

**Comment by jhilden** [comment]
They probably have all the audio & light equipment there that we need (speakers, mixer, subwoofer, ....).  However, we really need somebody in Cologne that knows a little bit about this stuff and can take care of deciding what we need and how to operate it.  Do you know anybody?

For example these are the mounted speakers they have in the main hall:  ![speaker](https://dl.dropboxusercontent.com/u/409736/railscamp_venue/2013-06-07%2010.03.00.jpg)

**Comment by jhilden** [comment]
Created a new ticket for projectors #28

**Comment by jhilden** [comment]
As far as I can remember @railsbros-dirk is probably going to be so kind to help us with this topic.  Let's go and visit the venue together to figure out what we will need.  I think you said something about 9.7., yes?

**Comment by code-later** [comment]
Yeah, I will try as good as I can to help with this stuff. 9.7. sounds good to me. Can we drop in anytime we want or do we need an appointment. I would prefer if could go after 15:00. Would this be possible?

**Comment by DonSchado** [comment]
how much budget for the dj?
On which days? 
How many hours?
What kind of music genre? ;)

**Comment by jhilden** [comment]
Let's talk about DJ in issue #36

**Comment by cice** [comment]
hey guys, i'm attending the railscamp and have been following the discussions around here. i'd like to contribute. i have a 600W PA system, which i could bring along, if you have use for it (eg. get some music into a small-to-midsized hall). my mixer is broken though, so it would be just amplifier and 2 speakers, and maybe a wireless microphone. cheers! Marian

**Comment by raucao** [comment]
That would be splendid for the hack tent and beer garden outside I think!

**Comment by jhilden** [comment]
Here are the notes form the meeting at the venue today:  https://github.com/railscamp/railscamp-germany-2013/wiki/MeetUp-Notes:-2013.railscamp.de---Audio-&-Video

@cice that would be awesome if you could bring your system.  Would it be possible that you could already be at the venue Friday at noon, so we can set everything up before the masses get there?

**Comment by klaustopher** [comment]
Just a remark: What about speakers not using a mac? If the only connection to the projector is via AppleTV, they cannot participate.

**Comment by raucao** [comment]
> If the only connection to the projector is via AppleTV, they cannot participate.

That would not be acceptable in my opinion.

There are other general-purpose A/V radio solutions that work with just cables plugged into the computer. Maybe we have to look into that, if we don't have A/V cables on the stage.

> Es gibt KEIN Rednerpult

How is that supposed to work? As a developer/hacker event, we need the ability to give live coding demos and to not do their presentations with remotely-controlled Keynote slides. No?

**Comment by jhilden** [comment]
We will figure out the Rednerpult thing during setup on the Friday, we are flexible in that regard and will find the best solution.

I guess I'm with @skddc on the Apple TV and would vote for an old school VGA cable :)

**Comment by cice** [comment]
@jhilden that should be no problem, can you estimate when? i'm located near Jülich, so it's not that far.

**Comment by code-later** [comment]
Regarding the AppleTV, if there are only slides, you still can hand them over a Mac guy. But I see the problem when it comes to live coding. Getting a cable up there just isn't very easy, but we will figure something out. And no, VGA is _not_ an option ;-)

Regarding the speaker's desk: We can still put some small table on the stage but I prefer to have no table on stage as the default.

**Comment by klaustopher** [comment]
Well, both connections (DVI and VGA) start to get problems when running them over 10m ... VGA starts to get blurred, DVI simply stops working ... Both connections need amplification...

**Comment by code-later** [comment]
That's what I wanted to say with "isn't very easy". Not using VGA is more like "it's 2013" ^^

**Comment by raucao** [comment]
> Well, both connections (DVI and VGA) start to get problems when running them over 10m

As I said, there are radio-solutions available that bridge the distance, but use cables to both devices on the ends.

> We will figure out the Rednerpult thing during setup on the Friday, we are flexible in that regard and will find the best solution.

Yer, I don't see an issue there. Just needs to be there, so people can properly use their notebooks on stage. We can manage with some empty crates, though. Always works somehow.

**Comment by code-later** [comment]
@skddc a radio solution is a great idea, maybe whoever is responsible for getting as a projector (railscamp/railscamp-germany-2013#28) should take care of this?

**Comment by raucao** [comment]
Apparently there are even cheaper transmitters using ethernet. Check this out e.g.: http://www.ebay.com/itm/Extron-TP-T-15HD-A-Cat-5-Transmitter-/360692824818?pt=US_Audio_Video_Transmitters&hash=item53faf7baf2

**Comment by klaustopher** [comment]
I just talked to our AV person at work. He said that it's no problem using DVI over long distances and that he has used longer cables than 10m in setups he used. When using 1024x768 resolution, you can go around 50m with regular cables, Full-HD resolution works for around 30m. If longer distances are needed, there are [DVI-fibre cables](http://www.kramergermany.com/products/model.asp?pid=783&sf=167#1) that you can rent.

**Comment by raucao** [comment]
Sounds good! 1024x768 is enough for presentations anyway.

**Comment by cice** [comment]
if you have use for my PA system, i need to know when to be there, because i need to take a day off and organize a bigger car ;)

**Comment by raucao** [comment]
Friday afternoon.
