### ISSUE TITLE
Rails Girls apps hackday

### ISSUE THREAD

**Issue by svenfuchs** [railscamp/railscamp-germany-2013#30]
Not sure if this is the right place for posting this.

And I'm also not sure how far the idea of sub-hosting a Rails Girls camp, or just infiltrating the camp with 50% Rails Girls attendees has been discussed. We've certainly had a few excited chats with Sebastian on our office terrace :)

But, basically, **if** Rails Girls students will be invited and actually can attend with a significant number, then here's an idea for a common hacking goal that could be recommended to attendees:

While working on RailsGirls Summer of Code I've realized how much the entire movement is built on tools that could be just so much better, with very little effort. This is probably mostly due to the reason that the movement is entire grassroots, and every new team just picks the tools they're used to. Not being developers themselves most of the times this will be Google docs forms and spreadsheets, maybe copying over csv files and pasting them to MailChimp.

While all of this works ok some simple Rails apps could help with this tremendously.

The idea behind what's being labelled "Rails Girls Apps" is to create a collection of simple Rails apps ... **together** with Rails Girls students. Apps where the emphasis is not on technology, sophistication, "the latest hype" etc, but on hackability _for newcomers_, ease of use and usefulness.

Simple examples: being able to register a new group/city for a Rails Girls workshop, then have the ability to accept registrations from attendees, send out news letters, have a standard homepage/announcement, ... 

Another usecase is: there are a myriad of project and study groups forming worldwide. Berlin has a good dozen alone, and we all don't know of each other! No one know who's active where, doing what, meeting when etc.

We'd hope that having a bunch of useful global Rails Girls app might kick the movement from being a highly infective, but yet in each instance locally confined movement to a globally connected community.

If that makes any sense ...

Anyhow. The idea would be to hack on this together at Railscamp. We'd have to prepare a list of apps and define usecases, features etc. Then groups of Rails Girls student could hack together with regular Rails devs and change the world :)

**Comment by raucao** [comment]
You know I already think it's a great idea, so just to add this for completeness: we'll definitely have plenty of space for hacking! And as soon as we know how many Rails Girls are participating, we can specifically plan for this, both in regards to location and times. So let's do it! :)

**Comment by drblinken** [comment]
Hi Sven, just found this post checking out the railsgirlsberlin mailing list to post the app Bjelli and me have been working on - which is designed to do part of what you suggested: 

> Simple examples: being able to register a new group/city for a Rails Girls workshop, then have the ability to accept >registrations from attendees, send out news letters, have a standard homepage/announcement, ...

see https://github.com/learnery/learnery 
cheers 

Béla

**Comment by svenfuchs** [comment]
Nice, looks interesting!

Definitely gonna look into this more! 

Thanks :)

**Comment by raucao** [comment]
We should make some progress on this soon, if we want to reserve tickets...

**Comment by svenfuchs** [comment]
i just had exactly the same thought :)

what's needed to make progress? is there an announcement, yet?

might be best to just put it on the website, and then start spamming everyone through email/twitter etc?

**Comment by raucao** [comment]
We do have a blog, where we can put announcements. I'm not entirely sure what the current plan is and what's important to communicate, so it would be good if you or someone involved with planning the track could write it up.

How was the feedback so far? I have no idea how many tickets to reserve. I would have proposed 50 of the 200. Only the first 100 go on sale on Wednesday, so we still have time to decide.

**Comment by raucao** [comment]
@svenfuchs Any news on this? We should send out invitations asap. Only 4 weeks to go...

**Comment by svenfuchs** [comment]
sorry, i haven't been able to put time into this. i've talked to some of the ruby monsters yesterday and some are planning to come. also, liane contacted me for a skype call today.

**Comment by raucao** [comment]
Is anyone still planning to write something up or help us in any way to get out some official announcement and probably a separate track in the schedule?

**Comment by svenfuchs** [comment]
talked to tatjana, she's on it!

**Comment by tatjanala** [comment]
Hey, I wrote a little text to put on the RailsCamp website (blog?) and on facebook etc. Can you guys check it out and if necessary add stuff...

What do you think?

RailsGirls at RailsCamp

RailsGirls will be part of RailsCamp Germany on July 27/28. We think this will be an amazing opportunity to meet RailsGirls students & coaches from all over Europe!

RailsCamp Germany (http://2013.railscamp.de) will take place at an amazing venue in Cologne and it would be great to have all RailsGirls here to celebrate and hack with us!

A RailsCamp is basically just a great place to meet over the weekend. There is no fixed schedule, at least none given by the organizers. Instead talks can be planned/given spontaneously. Often times people hang out and hack together and there will be fun activities, party etc. The venue is huge so there will be enough space for us where we could do RailsGirls specific talks, exchange thoughts, and maybe even hack on some RailsGirls Apps (https://github.com/railscamp/railscamp-germany-2013/issues/30) in teams of RailsGirls students and Rails devs.

Even though this event is called "RailsCamp Germany" everyone is invited, so please feel free to join us there!
Ticket prices are basically "pay what you want", but we suggest a price of 25 EUR: http://2013.railscamp.de/tickets/ 

Happy to see you all at RailsCamp :)

Love from Cologne

**Comment by jhilden** [comment]
Little change suggestion:  "Even though this event is called "RailsCamp Germany" everyone **from everywhere** is invited"

Besides that, really awesome.  Let's create a post on the RailsCamp Website from this text.

**Comment by raucao** [comment]
I'm in the process of writing and publishing the next few posts. First one today. I'll handle it.

**Comment by svenfuchs** [comment]
great to see progress here. thank you so much @tatjanala :heart:

**Comment by tatjanala** [comment]
YAY! I'll put the text on our facebook page and we`ll start to twitter like crazy!

**Comment by jhilden** [comment]
Please reopen this issue, if you still have RailsGrils stuff that you want to organize before the event, outside of the session planning app.
