### ISSUE TITLE
Twitter wall(s)

### ISSUE THREAD

**Issue by raucao** [railscamp/railscamp-germany-2013#33]
Would be great if somebody could set up a Twitter wall on the Web somewhere, so we can put it on the screens and maybe switch automatically between the schedule grid and that. We'll use "rcg13" as the official hash tag.

**Comment by galfert** [comment]
If nobody else already has a favorite Twitter wall that we should use I could have a look to see what's available. I think something that also shows photos, for example from Flickr, would be nice.

**Comment by jhilden** [comment]
@galfert would be cool if you could look for something

**Comment by Uepsilon** [comment]
I've search the web a little bit but it seems there is no free version of a twitter wall that is capable of displaying pictures - except for those old ones with silverlight which i cannot get running with ubuntu ;). 

I think [ThinkWall](http://www.thinkwall.com/) seems nice from their videos but it is not free. I'll ask them to tell me what their prices are or if there can be manged something without payment and a logo on the twitterwall or so. Would that be Ok?

**Comment by raucao** [comment]
Just do it. No need to ask for permission.

**Comment by Uepsilon** [comment]
> Hi Maxim
> 
> Thanks for contacting ThinkWall, the Rails Camp looks very interesting and we would be happy to work with you on it. Unfortunately we cannot offer the option of giving away ThinkWall in exchange for advertising our own logo, however you may give over as much space on the screen as you would like to to other brands; this is something that many of our previous clients have opted to do.
> 
> In terms of costs for the event, we charge £500 for the custom design of the ThinkWall screen, the training of you staff in how to use the software and the setup. We will then quote you for such things as the number of screens at the event, whether you would like on site support etc. A rough estimate for a small/medium sized event would be around £1000.
> 
> If you would like to learn more about ThinkWall then please let me know and I will be happy to set up a conference call at your convenience to discuss your event and desired setup. Please see below for some of our previous case studies.
> 
> http://thinkwall.com/ThinkWallCaseStudies.pdf
> 
> Kind Regards
> 
> David

Damit hat sich das wohl erledigt... Bleibt also entweder OpenSource oder irgendwer baut schnell was schickes (was im Optimalfall auch Bilder kann ;))

**Comment by galfert** [comment]
Yer, that's also what I found. All the reasonably good ones put up some ridiculous prices.

I started to hack on a little app with Twitter and Flickr integration on the weekend. I think I can build something useable for the camp from that.

**Comment by Uepsilon** [comment]
If there is a problem with displaying the twitterwall (aka hardware?!), we may have a setup for another project which comes with at least some displays. We might use them to display the twitter-wall too (let's decide that during the event, setting it up should not take that long if the wall is running).

**Comment by badboy** [comment]
info-beamer was used at 29c3, is written in lua and comes with an already written twitter script. See http://info-beamer.org/, https://github.com/dividuum/info-beamer, https://github.com/dividuum/info-beamer-nodes

**Comment by raucao** [comment]
@badboy Sounds good!

**Comment by colszowka** [comment]
:tada:
