### ISSUE TITLE
Warmup Party and Party

### ISSUE THREAD

**Issue by koos** [railscamp/railscamp-germany-2013#36]
Hi,
what about parties? :)
There are two options in my opinion:
- doing everything in the Abenheuerhallen
- splitting it between Abenteuerhallen and "trash-chic" (a bar across the location ~ 1 min. walk) - http://www.trash-chic.com/pics-und-videos/

(doing a "official" party in the city is not an option in my opinion - people can decide by their own but we should keep everything more or less in one place)
# Idea No. 1:
- Warmup Party (friday) in "trash-chic" - drinking beers, talking
- Party (saturday) in Abernteuerhallen - live concert (preferably a band from the community), BBQ
# Idea No. 2:
- Warmup Party (friday) in Abenteuerhallen - live DJ, beers, talking, (BBQ)
- Party (saturday) in Abernteuerhallen - live concert (preferably a band from the community), BBQ

If we decide on an option I can organize the parties.

**Comment by jhilden** [comment]
I vote vor Idea No. 2, because I think it's nice to have the whole event in one place and I think a party at the venue would better suit everybody:  those that want to party and those that just want to hang out or even code.

**Comment by raucao** [comment]
I voter for option 1, because after setting up the venue for a whole day, I don't want to have a party before the event and then clean everything up before the event. I'd much rather chill out down the street after hours of getting everything ready. Also, it's flexible for the setting up then, because otherwise we'd have a deadline for that, which is also not nice.

**Comment by raucao** [comment]
Just saw that Trash Shic wants people to go inside at 10pm. That's a bummer. Maybe we can do something in our beer garden? Just don't see the point in using the main hall on Friday night.

**Comment by koos** [comment]
I don't know a beer garden nearby. And even if - I think most of them also want's people to go inside. Then I prefer option 2 too and lets open a beer garden by ourselfs behind the main hall.

**Comment by raucao** [comment]
We have a beer garden set up behind the house. That's what I'm talking about. We can have our own outdoor party without using the hall and with a license until 5am. ;)

**Comment by koos** [comment]
ok, 
so I'll have a look for bands and dj's for the evenings ;)

On Jun 24, 2013, at 5:00 PM, Sebastian Kippe notifications@github.com wrote:

> We have a beer garden set up behind the house. That's what I'm talking about. We can have our own outside party without using the hall and with a license until 5am. ;)
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Jan Kus

Railslove GmbH
An der Bottmühle 5, 50678 Cologne, Germany  

Mobile +49 (0) 179 13 53 53 9
Twitter @koos

Registergericht: Amtsgericht Köln, HRB 70843  
Geschäftsführer: Michael Bumann, Jan Kus, Tim Schneider

*\* We're proud of building: http://dealbaseapp.com - a web based deal tracking and portfolio management tool **

*\* Visit Cologne for a one week hack-tech-biz-creativity festival this year! June 17th - 23rd. http://interactive-cologne.com **

*\* this email brought to you by ✓ http://instantcheckmark.com ✓ **

**Comment by raucao** [comment]
Great!

Keep in mind that people at confs and camps usually like to chat all night, so don't book like 10 bands and DJs. ;)

**Comment by koos** [comment]
1 band (~45 min.)
1 dj (playing continously music)

On Jun 24, 2013, at 5:22 PM, Sebastian Kippe notifications@github.com wrote:

> Great!
> 
> Keep in mind that people at confs and camps usually like to chat all night, so don't book like 10 bands and DJs. ;)
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Jan Kus

Railslove GmbH
An der Bottmühle 5, 50678 Cologne, Germany  

Mobile +49 (0) 179 13 53 53 9
Twitter @koos

Registergericht: Amtsgericht Köln, HRB 70843  
Geschäftsführer: Michael Bumann, Jan Kus, Tim Schneider

*\* We're proud of building: http://dealbaseapp.com - a web based deal tracking and portfolio management tool **

*\* Visit Cologne for a one week hack-tech-biz-creativity festival this year! June 17th - 23rd. http://interactive-cologne.com **

*\* this email brought to you by ✓ http://instantcheckmark.com ✓ **

**Comment by raucao** [comment]
You da man.

**Comment by jhilden** [comment]
We/I should clearify with the venue, that it is really possible to have a
party with live music outside the hall. But I think it should be ok.

**Comment by raucao** [comment]
We don't need live music on Friday, which means we don't need it outside the hall ever.

**Comment by colszowka** [comment]
Beergarden right at the venue sounds great! One slightly stupid question: Where does the beer (and other drinks) come from? Are they available at/by the venue?

**Comment by jhilden** [comment]
@colszowka see issue #5. Why do you ask?

**Comment by raucao** [comment]
@colszowka We have fridges inside, yes.

**Comment by colszowka** [comment]
@jhilden Oh, I was just curious whether the venue has staff who take care of this or if you're rolling your own or everyone needs to bring stuff themselves from a Büdchen :)

**Comment by jhilden** [comment]
OK :)  No we will order enough drinks for everybody.  But we will certainly need some volunteer help staffing the bar and so on.  Since this seems to be a topic of interest to you, would you want to take on (some) responsibility for this? ;)

**Comment by raucao** [comment]
We'll have to organize it ourselves. So I think the idea is to put drinks in the fridge inside beforehand and just put out cold crates during the party outside for everybody to grab.

On the second day, we'll need volunteers for tending to the bar inside.

**Comment by colszowka** [comment]
Hehe, sure, I'd help out for an hour :) I'm sure it will be no problem to organize this ad-hoc at the venue on saturday morning

**Comment by jhilden** [comment]
Marco asked some questions in #3

> how much budget for the dj?

Don't know.  I think the better approach is to get some prices and to take the best offer.

> On which days? 

I think it would be great to have "some sort of DJ" on both days, but to have the bigger party on Saturday, as everybody will be there then.

> How many hours?

No clue.

> What kind of music genre? ;)

Definitely good music! ;)

A friend of mine who is a DJ would be interested to play.  He's playing something like big beat, house, old school stuff:  https://soundcloud.com/steveclash  What do people think?

**Comment by raucao** [comment]
I'm not sure why we need a professional DJ. It's not like we're doing a dance party or something. If people feel like it, they can take over the sound system, and if not, then we'll just play Internet radio or Spotify or something, like during the day. I can also create a nice playlist for the night, and I know we have a few DJs among the participants as well.
