### ISSUE TITLE
Geekstammtisch @Railscamp

### ISSUE THREAD

**Issue by code-later** [railscamp/railscamp-germany-2013#37]
As you already know the Geekstammtisch Podcast is one of the small sponsors. Independently from this we would like to record two special episodes directly at the camp. They should contain short interviews from different attendees at the camp talking about their experience and what they learned.

@skddc suggested even a live recording session, which sounds great. Additionally we could host a session about podcasting itself, if someone would be interested.

We would take care of equipment and everything else related to this issue. Are you interested in something like this?

**Comment by jhilden** [comment]
Absolutely interested.

**Comment by timbuchwaldt** [comment]
+1

**Comment by moonglum** [comment]
:+1:

**Comment by markmcconachie** [comment]
+1

**Comment by jhilden** [comment]
Closing this issues because I don't think there is anything else to organize here.  Be sure to submit your podcasting session in the session management tool.
