### ISSUE TITLE
Participant survey

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#39]
To activate participants and to ask them some questions that are important for the event organisation, we want to send out a survey with some questions sometime before the event.

Here are some of the questions:
- Where are you planning to stay during the Railscamp?  a) bring my sleeping bag/pad and sleep at the venue  b) I have accommodation somewhere else  c) Not sure yet
- Are you planning to possibly do a session at the Camp?  Tell us about it.
- Could you imagine helping out before/during/after the camp with organizational stuff?  If yes tell us about it.  You can find many possible things to do in the GitHub issues.
- Do you want a t-shirt?  If yes, what's your size.  (only if we will have t-shirts)
- Are you a vegetarian or have any other dietary restrictions we should be aware of?
- Anything else you want to let us know before the event? 

We were talking about using Google Forms (or however it's called for the survey).  We should send out the survey sometime between the 12th and 17th of July.

**Comment by raucao** [comment]
Good idea!

No need to tell us about sessions, when we have the session planning tool anyway. Let's not collect data in various places. Also, the "could you imagine helping out" can be communicated when we announce the session planner or in a separate call for setup/teardown volunteers.

Let's keep it as short as possible so that many people participate.

**Comment by Uepsilon** [comment]
I like the Idea of that, but I guess with the Discussion about Prism n Stuff in mind, Google may not be the best Host for Data (even when it's not directly linked to any personal data). Where do we host the RailsCamp-Page? Can't we host it there? 

I guess there are several tools for Surveys, here's just one I found recently: 
[Lime Survey](http://www.limesurvey.org/) | [Demo](http://www.limesurvey.org/en/about-limesurvey/license)

Seems to use PHP + MySql | Postgres.. Well, maybe we'll finde some Ruby-App :) Although I wouldn't mind to use this one.

**Comment by raucao** [comment]
The RailsCamp page is hosted as the gh-pages branch of this repo.

If you want to set up a survey tool, go ahead (and let everyone know). We don't need full names in the Google form, though, so I think it's ok for this.

**Comment by Uepsilon** [comment]
I'll try and get Lime Survey running on Heroku / Uberspace. I'll then share the login-Data with @jhilden (i know his email :D) so you can setup the service to your benefits.

**Comment by Uepsilon** [comment]
Okay, it's running and I created an account for @jhilden (you should receive an email). But I must admit, you can setup a shitload of settings. nice!

**Comment by Uepsilon** [comment]
Any news? What about a Subdomain? Or do you plan to integrate it via iframe into the RailsCamp-Page?

**Comment by jhilden** [comment]
I played around a little bit with it last week and even thought it's a
little more complicated that I would like (e.g. need different language
translations for the questsions), I think it will work.  We will send out
the Email with the survey link to all the ticket buyers.  So, no website
integration or subdomain.  Planning to do this today/tomorrow.

**Comment by DonSchado** [comment]
If you need some help today, let me now! Think we should get this out asap.

**Comment by Uepsilon** [comment]
@jhilden you are talking about the survey i send you or one you created with google forms?
With LimeSurvey you can narrow down the languages to german / english only, but i thought it would be better to have at least these 2 options. Anything i can help you with?

**Comment by jhilden** [comment]
It would be much better/easier to have only one language (same as on the website).

Maybe you could help by creating an LimeSurvey account for @DonSchado (marco@railslove.com) so he can also help with the Survey.  If we have the survey more or less ready maybe we can post a link to a little pilot test of the survey here to get feedback from others on the questions & answers (it's just important that the survey data can be reset after the pilot).

**Comment by Uepsilon** [comment]
I just created a new SuperAdmin with his email.

**Comment by jhilden** [comment]
OK.  Here is the current pilot version of the survey:  http://survey.uepsilon.ursa.uberspace.de/index.php/survey/index/sid/148912/newtest/Y

Please try it out and give me some feedback if there is anything that should be changed/added.   I will then send out the email and start the survey sometime this afternoon/evening.

**Comment by DonSchado** [comment]
![error](https://f.cloud.github.com/assets/685742/786846/6274551e-eac8-11e2-8d58-32d2300f2683.png)

**Comment by jhilden** [comment]
Hmm.  Can you let me know if this works?  http://survey.uepsilon.ursa.uberspace.de/index.php/survey/index/sid/148912/newtest/Y/lang/en

**Comment by DonSchado** [comment]
work's

**Comment by Uepsilon** [comment]
works for me without beeing logged in as an admin.

**Comment by raucao** [comment]
Works and looks great! Good job!

>  If there is anything in particular way you want to contribute, this is the way to let us know

I'm not sure that should be the way. Wouldn't it be better to add it to GitHub and/or the session tool?

**Comment by Uepsilon** [comment]
why is there a "newtest" in the link? I haven't found this name in the survey.. ;(

**Comment by Uepsilon** [comment]
Ah "newtest/Y" appears when you trigger a test via admin-panel. I don't know whether it has any influence on the statistic (does not seem so at least), but i guess we should strip it when sending the mail. So the correct URL would be
http://survey.uepsilon.ursa.uberspace.de/index.php/148912/lang-de for the german version 
http://survey.uepsilon.ursa.uberspace.de/index.php/148912/lang-en for the english version

**Comment by jhilden** [comment]
OK.  I have cleared the responses up until now and send out the email via eventbrite.  Let me know if there are any issues.

**Comment by moonglum** [comment]
Uhm, you didn't ask if the person is a lady or a gentleman, which is quite important for the T-Shirt IMHO.

**Comment by Uepsilon** [comment]
You cannot add a question when the survey is active. I'll add it tonight (so we won't miss any potential entries).

**Comment by raucao** [comment]
> Uhm, you didn't ask if the person is a lady or a gentleman, which is quite important for the T-Shirt IMHO.

The t-shirts are unisex, no? Do you want to order various kinds of shirts after all?

**Comment by moonglum** [comment]
I'm not sure, @DonSchado ?
I remember that there was quite a lot of mumbling by some ladies at Scottish Ruby Conf that they "will only wear that shirt for sleeping in it", because it was a male shirt.

**Comment by DonSchado** [comment]
Whooa, what a trap! :rabbit: 
Good point @moonglum!
But no panic. The American Apperal Site says it's **unisex size – women may prefer to order one size down**.

_phew_

**Comment by moonglum** [comment]
Ok, then we should add this piece of information to the survey :wink:

**Comment by cice** [comment]
there is an extra space at the end of the survey link in your email (http://survey.uepsilon.ursa.uberspace.de/index.php/148912/lang-en%20), which causes a 404.

**Comment by Uepsilon** [comment]
fixed via htaccess

**Comment by jhilden** [comment]
@Uepsilon thanks a lot for fixing the link!

We have 38 complete responses so far and I think we should be able to decently extrapolate t-shirt interest from that.  I added a note about the unisex sizes for people that haven't filled out the survey yet.
