### ISSUE TITLE
Catering (during the day)

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#4]
We need somebody to take care of catering during the day.  Probably Breakfast and Lunch on both Saturday & Sunday.  Maybe also some snacks.

For past events we have gotten food from, e.b. http://www.habibi-koeln.de/

**Comment by raucao** [comment]
Nope, for the past RailsCamps we had sandwiches n stuff.

That was actually a great concept. We had food that was both breakfast and lunch, and that you could eat all day, effectively eliminating the need for a lunch break. And everybody could eat when they wanted, anytime. Let's do that again!

**Comment by jhilden** [comment]
Sounds good  :+1: 

(But Habibi is still very tasty and can also be eaten all day)

**Comment by jhilden** [comment]
Another option:  http://www.mariecurry.de/    That way we wouldn't have to organize anything inside the venue.

**Comment by raucao** [comment]
Does someone know where the wraps and stuff came from on the last RailsCamp? /cc @bumi

**Comment by moonglum** [comment]
Sandwiches sound like a great idea, and also thumbs up for Habibi :wink: Any one with experience to plan food for so many people that spend the entire day (and for some the entire night)?

**Comment by raucao** [comment]
With cold finger food we only need enough of it and place tablets in one or 2 places. That's the beauty of it.

**Comment by thilo** [comment]
Any numbers for the costs?

**Comment by jhilden** [comment]
@tatjanala agreed to take care of this and hopefully should have some numbers for us soon

**Comment by tatjanala** [comment]
Hey everybody! I think at the last RailsCamp we had Wraps from KAILUA, I don't know if they still exist, but I can check it out. If we agree on sandwiches and stuff cafecafe could be a good choice too. They offer plates with panini, bagels or sandwiches as well as different salads and cakes/muffins etc.
One plate with 24 bagels costs round about 65€ (sandwiches are cheaper). What do you say?

**Comment by tatjanala** [comment]
Habibi could be a option for lunch on Sunday as well?!

**Comment by tatjanala** [comment]
I`ll ask cafecafe for an offer. 200 people two days, right?

**Comment by raucao** [comment]
Yup.

**Comment by tatjanala** [comment]
Heyhey, here is the first offer (cafe cafe)

Vorschlag 1 (beispielsweise für Sonntag):
100 Bagels, halbiert (also 200 Hälften), pauschal 293,70 €
100 Ciabattine, halbiert (also 200 Hälften), pauschal 308,00 €
100 Sandwiches, geviertelt (also 400 Viertel), pauschal 360,00 €
Summe: 961,709 €

Vorschlag 2 (beispielsweise für Samstag):
200 Salate, halbe Portionen 560,00 €
50 Bagels, halbiert, pauschal 146,85 €
50 Ciabattine, halbiert, pauschal 154,00 €
Summe: 860,85 €

Vorschlag Süßes:
Brownies, geviertelt, für 2,00 €
Flapjacks, halbiert für 2,00 €
Muffins 1,70 €
Cup Cakes 2,00 €
Pasteis de Nata 1,60 €

What do you say? We're still waiting for two more offers...

**Comment by moonglum** [comment]
Sounds delicious :wink: I have no idea if this is enough / too much at all, but the prices seem to be ok IMHO.

**Comment by raucao** [comment]
Should probably be a bit more, because it's basically both breakfast and lunch. And how about some low-carb option? ;)

**Comment by tatjanala** [comment]
We thought about having fruits as low-carb option to all the sandwiches ;) And Denise suggested "Trifles" (Man braucht nur Becher und Löffel für drei Schichten knuspriges, cremiges und fruchtiges. Zum Beispiel zerbröselte Kekse oder Müsli plus Pudding und/oder Joghurt plus Obst - alles im Becher über einander schichten und genießen! Passt morgens, mittags, abends und zwischendurch!) I don't know if this is low-carb, not really, right? What else would you suggest?

**Comment by thegcat** [comment]
Fruits are only partially low-carb (depending on their fructose contents), see also http://lowcarbdiets.about.com/od/whattoeat/a/whatfruit.htm (for example, google yields some other lists too) (yeah, the page is a pita to look at :-( )

**Comment by tatjanala** [comment]
Do you guys have some other suggestions for low-carb snacks? I don't know much about low-carb food...

**Comment by jhilden** [comment]
@tatjanala your suggestions sound very good.  we should just switch the days, because people might leave a little earlier on Sunday, so we won't need as much food there.

What else do you need to finalize this?

**Comment by tatjanala** [comment]
We are waiting for an other offer, but we`ll decide and order on Friday!

**Comment by tatjanala** [comment]
Hey, the other offer was way to expensive so we decided to order at cafecafe. We can wait for the order till next wednesday, so we know better how many people will come...
