### ISSUE TITLE
Meetup notes for the audio equipment

### ISSUE THREAD

**Issue by larsvegas** [railscamp/railscamp-germany-2013#40]
Hey,

find the notes here: https://github.com/railscamp/railscamp-germany-2013/wiki/MeetUp-Notes:-2013.railscamp.de---Audio-&-Video

@railsbros-dirk, @jhilden may you double check and send it back to Dirk, so he will not "forget about it" ;)

**Comment by code-later** [comment]
Thanks Lars for writing this done. Looks good. I just added the subwoofer and I remember the distance between the projector and the screen is 6 meter.

**Comment by jhilden** [comment]
Closing this extra issue in favor of #3   Will copy the link to the notes over.  Thanks a lot @larsvegas & @railsbros-dirk
