### ISSUE TITLE
Proposal: Arcade Fighting Game Tournament

### ISSUE THREAD

**Issue by code-later** [railscamp/railscamp-germany-2013#41]
Hi friends,

maybe I'm alone with this, but I quite like those arcade fighting games :-) And as we have some big screen and a nice PA what about some fun tournament? I could bring a PS3 with some games and two arcade sticks.

If anyone is interested in this kind of activity please let me know. If not, just close this issue ;-)

**Comment by raucao** [comment]
The early beta of the session planning tool is online at http://sessions.railscamp.de – go ahead and enter session proposals already! It's still buggy and unfinished, but you the more we have in there, the better.

Be sure to add issues or comments to https://github.com/railscamp/railscamp-activities/issues when stuff breaks. ;)
