### ISSUE TITLE
Marketing

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#42]
Since we still have a good number of ticket spots left, let's go and do some marketing.

Here are some potentially worthwhile things to try:
- email/twitter to ruby usergroups
- write to the main ruby news outlets:  rubyflow, ruby weekly, ruby5, ...
- invite other rubyists personally
- do some marketing in our neighbor countries:  netherlands, belgium, poland, france, switzerland, austria, ...

Any other ideas are welcome!

**Comment by jhilden** [comment]
I just posted our event to RubyFlow:   http://www.rubyflow.com/items/9564-railscamp-germany-2013-cologne-july-26-28

**Comment by jhilden** [comment]
Here is a post on Facebook that you can share with all your friends:  https://www.facebook.com/Railslove/posts/681921111833660

Do you think it makes sense to create an event for the Railscamp on facebook??

**Comment by raucao** [comment]
> Do you think it makes sense to create an event for the Railscamp on facebook??

I for one don't.

I'll extend ticket supply today and will publish another blog post about it. There's only 10 left, so we sold 90% of the first batch.

**Comment by marcel12bell** [comment]
Here the List of the Postings:
google+:
https://plus.google.com/117385509303644635034/posts/Kbd2aF1ywD7
https://plus.google.com/117385509303644635034/posts/ENcWoWK2bwD
https://plus.google.com/117385509303644635034/posts/AZhSk6wJRkL
https://plus.google.com/117385509303644635034/posts/bYFYJxScYNm
Foren:
https://www.ruby-forum.com/topic/4415692
http://forum.ruby-portal.de/viewtopic.php?f=7&t=25332

**Comment by raucao** [comment]
@marcel12bell Cool, thanks!
