### ISSUE TITLE
Stickers

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#43]
@DonSchado will check if we can get stickers with the Railscamp logo?

**Comment by lliane** [comment]
Heyho. 

Hier sind Entwurf und Angebot. 
Machen?

![bildschirmfoto 2013-07-18 um 14 38 35](https://f.cloud.github.com/assets/1529276/819007/5719986c-efa7-11e2-9faf-29d7d6d65dc4.png)

![bildschirmfoto 2013-07-18 um 14 41 38](https://f.cloud.github.com/assets/1529276/819008/687f8274-efa7-11e2-88a7-af0533ba7b7e.png)

**Comment by DonSchado** [comment]
Sind bestellt! Thx @lliane! :)

**Comment by raucao** [comment]
What about the flame?

**Comment by raucao** [comment]
Also, this one would have to be transparent for me personally to put it on my laptop.

**Comment by jhilden** [comment]
I'm contra transparent ;)

**Comment by lliane** [comment]
Bezahlt und bestellt.

**Comment by DonSchado** [comment]
\o/

**Comment by DonSchado** [comment]
stickers arrived
