### ISSUE TITLE
Participant Checklist

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#44]
Here will will collect stuff that participants can/should bring along:
-  Mehrfachstecker
- Smartphone for thethering
- Laptop
- Sleeping bag + sleeping pad
- Session ideas
- Towel (Don't Panic!)
- Fan ("Ventilator")

**Comment by jhilden** [comment]
Since it looks like the wather is going to be quite hot on the weekend **participants should definitely bring along stuff to cool them down**.  Beware: The venue is not so well insulated and it's going to be very hot in there.

Suggested things to bring along:
- Fan / Ventilator
- Light clothes
- Swim wear (see #47)
- Water pistols
- whatever else cools you down

**Comment by moonglum** [comment]
Ethernet Cables, as mentioned in #46

**Comment by colszowka** [comment]
How bad will it be with the heat, and do we still need sleeping bags? Also, I could not find any info on this, so on what days is sleeping at the venue possible? Only friday&saturday?

**Comment by jhilden** [comment]
Sleeping at the venue will be possible Friday->Saturday  and  Saturday->Sunday.

**Comment by jhilden** [comment]
Since we are not going to have the fastest internet in the world and certain limits on the data volume, it might make sense to prepare for that by:
- downloading vagrant boxes
- offline documentation for gems
- helping to setup #46

Any other suggestions?

**Comment by jhilden** [comment]
I take that back, internet is probably going to be pretty ok.
