### ISSUE TITLE
Setup on Friday

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#45]
Who will be there?

Morning
- [x] Jakob Hilden
- [x] Lars Wolf
- [x] Dirk Breuer

Afternoon:
- [x] Georg L. (BBQ shopping)
- [x] Jan Kus
- [x] Marcel
- [x] Marco S.
- [x] Basti Kippe
- [x] Garret
- [x] Maxim K. (from 5pm on)
- [x] Tim Buchwaldt (wifi)
- [x] Klaus Z. 

Tasks:
- [x] Audio setup
- [x] Stage
- [ ] Get the projectors
- [ ] BBQ shopping
- [ ] Recieve drinks delivery
- [ ] Uplink setup
- [ ] Wifi setup

**Comment by raucao** [comment]
I'm in.

**Comment by galfert** [comment]
I can only take the train on friday morning, but I'll be there for the afternoon shift :)

**Comment by timbuchwaldt** [comment]
I will be there :) From whatever time is necessary on, I am on vacation

**Comment by klaustopher** [comment]
I can be there around noonish, bring the @putpat provided beer and can help with some of the AV or Wifi Setup

**Comment by jhilden** [comment]
@timbuchwaldt could you also bring the Liegestühle from adcloud?  Or do you have a plan how they could get to the venue?

**Comment by timbuchwaldt** [comment]
@jhilden I won't have the transport capacity - who acked having them?

**Comment by Uepsilon** [comment]
@timbuchwaldt i'm driving on friday by car, so i can stop at adcloud and help you drive them over.. around 5pm..

**Comment by bascht** [comment]
I'm available all day on friday - if needed I could also rent a bus / van from db carsharing.

**Comment by jhilden** [comment]
@bascht that's awesome.   @koos was talking about doing the same thing, maybe you two want to team up.

We could use a car to get Liegestühle from Adcloud,  Bean Bags and stuff from the Railslove office, etc.

**Comment by koos** [comment]
@bascht I thought to rent a Flinkster VITO at Maastrichterstr. Here is the tour I have in mind:

A. Pick up car
B. Pick up Sitzsäcke and Liegestühle 
C. Pick up a Liegestuhl
D. Pick up other Stuff
E. Venue
F. Bring back car

https://maps.google.com/maps?saddr=Maastrichter+Stra%C3%9Fe,+Cologne,+Germany&daddr=Adcloud+GmbH,+Venloer+Stra%C3%9Fe,+Cologne,+Germany+to:Lindenstra%C3%9Fe+75,+Cologne,+Germany+to:Railslove+GmbH,+An+der+Bottm%C3%BChle,+Cologne,+Germany+to:AbenteuerHallenKALK,+Christian-S%C3%BCnner-Stra%C3%9Fe,+Cologne,+Germany+to:Maastrichter+Stra%C3%9Fe,+Cologne,+Germany&hl=en&ie=UTF8&ll=50.931495,6.970825&spn=0.069998,0.130119&sll=50.931495,6.971512&sspn=0.069998,0.130119&geocode=FdJBCQMdyNtpACnJnSYgBCW_RzGq4RSbJg_NdA%3BFcFPCQMdmNVpACEEDoc89f7FmimNk3OPBSW_RzEEDoc89f7Fmg%3BFdIqCQMd0M1pACntQbBzAiW_RzEfwUQlE6bUaQ%3BFaYDCQMdnEFqACG5fg5-AnfcVymlQch_nSW_RzG5fg5-AnfcVw%3BFaY1CQMdY_NqACFNoHTIEz4oIiklxUHKZCa_RzFNoHTIEz4oIg%3BFdJBCQMdyNtpACnJnSYgBCW_RzGq4RSbJg_NdA&mra=ls&t=m&z=13

**Comment by bascht** [comment]
@koos Looks doable. Do you need a hand? :)

**Comment by koos** [comment]
Would be cool. I thought to start at 1 PM and finish at about 3-4 PM. I think we will have one or two more stops to pick up some stuff.

**Comment by raucao** [comment]
Drinks will arrive circa 14:30!

**Comment by klaustopher** [comment]
I'll bring the sponsored beer around the same time

**Comment by netzvagabund** [comment]
I will be around at about 18:30 (depends on traffic), so I can't help much in advance. But you can count me in for the entrance (registration) and/or setting up the bar or something as soon as I arrive.

**Comment by endverbraucher** [comment]
I’m available from midday/afternoon tomorrow and could help on what ever is needed to be done. When should I be where?

**Comment by jhilden** [comment]
Just come over to the venue, whenever it's fine.  It's hard to predict what exactly will need to be done.

We could definitely still need somebody with a car who could pick up the projectors (but that would need to be before noon) and could make a run to the baumarkt later.

**Comment by raucao** [comment]
What does "morning" mean in the list above? When are the first people arriving?

**Comment by jhilden** [comment]
I will be at the venu from around 8:30-9:00 to check how we can get onto the roof.
The Richtfunk people will come over once they are done at the FH sometime after 9:00 I guess.

@railsbros-dirk & @larsvegas when did you want to come for the audio stuff?

@timbuchwaldt when will you an the wifi equipment be there?

@koos when will you bring the stuff from cowoco etc.?  (what else needs to be picked up, now that we can't get the AdCloud Liegestühle?)

I think the tent is supposed to come at 10:00 (@tatjanala ?).   The drinks at 14:30.  And probably more stuff that I forgot about.

**Comment by code-later** [comment]
Hi, @larsvegas and me will be there at 10:00. The foosball table will be delivered by 18:00.

Do we still need our Beamer?

**Comment by jhilden** [comment]
Another projector would be great.

**Comment by code-later** [comment]
No Problem, but I think I will bring it at Saturday along with the podcast equipment. Would that be okay?

**Comment by larsvegas** [comment]
2013/7/25 Jakob Hilden notifications@github.com

> AdCloud Liegestühle

What was the problem with them?
Lars

**Comment by timbuchwaldt** [comment]
@jhilden I will grab zakx at 10, then drive stuff through the city, hope to be there at 11 maybe

**Comment by larsvegas** [comment]
yep ok, @zakx and @timbuchwaldt have a key. i will not be there on saturday.

2013/7/25 Dirk Breuer notifications@github.com

**Comment by jhilden** [comment]
> > AdCloud Liegestühle
> > What was the problem with them?

@larsvegas They are unfortunately not available.  See https://github.com/railscamp/railscamp-germany-2013/issues/27#issuecomment-21482153

**Comment by DonSchado** [comment]
count me in for "morning" ;)
I'll pick up the T-Shirts about ~10 and come straight over to kalk

**Comment by timbuchwaldt** [comment]
@jhilden They are, we checked. If someone has a car big enough tomorrow, i can accompany him or her to the office and grab them

**Comment by larsvegas** [comment]
@jhilden As Tim said, Liegestühle are save. And @timbuchwald and
@railsbrosdirk pick them up on saturday, AFAIK.
Am 25.07.2013 20:44 schrieb "Tim Buchwaldt" notifications@github.com:

**Comment by jhilden** [comment]
@larsvegas That's great, that the Liegestühle are save.  @koos wanted to rent a small transporter tomorrow (Friday).  If you can give him the details where he can find them, who he should contact, he could probably pick them up.

**Comment by bascht** [comment]
@koos I'm at HomeOfficeCologne today, so I'll be right next to Brabanter Straße. If today's deployment will go down smooth meet up right there?

**Comment by koos** [comment]
Hey,
can you send me your mobile number? jan@railslove.com
Thx

On Jul 26, 2013, at 8:00 AM, Bascht notifications@github.com wrote:

> @koos I'm at HomeOfficeCologne today, so I'll be right next to Brabanter Straße. If today's deployment will go down smooth meet up right there?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Jan Kus

Railslove GmbH
An der Bottmühle 5, 50678 Cologne, Germany  

Mobile +49 (0) 179 13 53 53 9
Twitter @koos

Registergericht: Amtsgericht Köln, HRB 70843  
Geschäftsführer: Michael Bumann, Jan Kus, Tim Schneider

*\* We're proud of building: http://dealbaseapp.com - a web based deal tracking and portfolio management tool **

*\* this email brought to you by ✓ http://instantcheckmark.com ✓ **

**Comment by cice** [comment]
me and a colleague will arrive between 3 and 4 and bring the pa system, so if you need additional hands for anything, count us in.

**Comment by cice** [comment]
and our car broke down, could be a while

**Comment by raucao** [comment]
Damn. Good luck!
