### ISSUE TITLE
Local Services (rubygems mirror, gitlab, etc.)

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#46]
In order to be more independent from "the internet", there was the idea to create some local services such as a rubygems mirror or a local gitlab installation.

**Comment by jhilden** [comment]
Some qoutes from emails:

> Haben wir jemanden, der einen Server mit 2 Gbit LAN-Ports bereitstellen kann? Würde ich dann OpenBSD drauftun und darauf das limiting usw. machen.

## 

> Ich bin mir nicht sicher, wie verrückt die Idee ist, aber wäre es nicht eventuell eine gute Idee, eine Kiste hinstellen als Mirror von Ruby Gems?
> Die von Nick Quaranto vorgeschlagene Methode ist via [rubygems-mirror](https://github.com/rubygems/rubygems-mirror) und dann [Gem in a Box](https://github.com/geminabox/geminabox). Weil es stinkt einfach, wenn man `bundle` startet und dann dauert es zweieinhalb Jahre... :(
> Bisher habe ich noch nicht gefunden, wie groß so ein Mirror wäre. Aber ich denke mal, das sollte schon gehen!

## 

> Eventuell auch ne'n Git Server? Das kann man dann nach der Konferenz immer noch auf Github schieben, aber währenddessen will man ja schon vernünftig kollaborieren können.

**Comment by jhilden** [comment]
@timbuchwaldt we have an old spare MacBook at Railslove, don't know if that would be enough?

Could anybody else sponsor some hardware?

**Comment by raucao** [comment]
> @timbuchwaldt we have an old spare MacBook at Railslove, don't know if that would be enough?

That's enough.

**Comment by timbuchwaldt** [comment]
For Git and other local services, yes. @markmcconachie thought about bringing his Mac Mini, so just bring it along and we will have some buffer to start new services :)

**Comment by moonglum** [comment]
Awesome, @timbuchwaldt :dancer:

**Comment by raucao** [comment]
Forget about this one. ;)
