### ISSUE TITLE
Swimming pool

### ISSUE THREAD

**Issue by hagenburger** [railscamp/railscamp-germany-2013#47]
As it may get hot, we may need a pool. This one looks nice and is located close to Cologne: http://www.mietmeile.de/freizeit.kultur.sport.wassersport.events.messen.partys.pool.bornheim/xxl.schaumbecken-mieten.5699.php
- [ ] Check availability
- [ ] Organize transportation
- [ ] Water supply (a normal tab may be to small; I read about using fire hydrants at other websites)

**Comment by rin** [comment]
OMFG! 
+9000

**Comment by raucao** [comment]
Awesomesauce!

Would it be a bad idea to set it up only on one day? It might make it too difficult with the timing and transportation.

**Comment by Uepsilon** [comment]
I like the Idea! But is this a real pool or just something you can make some bubblewater with? How deep is it? Haven't found any infos about it. It says it's 2m deep but can you fill it that high (or at least 1m?).. 80m³ (1m_8m_10m) would cost roughly 250€. (wasser / abwasser).

**Comment by hagenburger** [comment]
Unless the person on the photo is 2.5 m in height, it can’t be filled 2 meters. Also there’s an entrance. I would guess you can fill it with less than 80 cm.

I found the original website for this:
http://www.crypton-event.de/katalog/aquamodule-mieten/schaumbecken-mieten.html

![pool](http://cdn.crypton-event.de/fileadmin/user_upload/bilder/alle_freigestellt_web/eventattraktionen/schaudance_arena_frei_02.png)

**Comment by jhilden** [comment]
I like the idea, however I don't know how doable it is.  I will talk with the venue tomorrow and ask about water supply and what they think about it.

Maybe we can think about smaller, easier kinds of "water fun"?   e.g. @koos is definitely going to order a bunch of water pistols.

**Comment by koos** [comment]
I'm thinking of this http://www.amazon.de/gp/offer-listing/B007N10E2S/ref=dp_olp_0?ie=UTF8&condition=all this http://www.amazon.de/Unbekannt-12-Poolkanone-Wasserspritze-Wasserpistole/dp/B0087BC8S6/ref=sr_1_5?s=toys&ie=UTF8&qid=1374513209&sr=1-5&keywords=Wasserpistolen and this http://www.amazon.de/Playtastic-Wasserbomben-Mega-Pack-500-St%C3%BCck/dp/B005RXJKM4/ref=pd_bxgy_toy_img_y

What do you think?

On Jul 22, 2013, at 7:09 PM, Jakob Hilden notifications@github.com wrote:

> I like the idea, however I don't know how doable it is. I will talk with the venue tomorrow and ask about water supply and what they think about it.
> 
> Maybe we can think about smaller, easier kinds of "water fun"? e.g. @koos is definitely going to order a bunch of water pistols.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Jan Kus

Railslove GmbH
An der Bottmühle 5, 50678 Cologne, Germany  

Mobile +49 (0) 179 13 53 53 9
Twitter @koos

Registergericht: Amtsgericht Köln, HRB 70843  
Geschäftsführer: Michael Bumann, Jan Kus, Tim Schneider

*\* We're proud of building: http://dealbaseapp.com - a web based deal tracking and portfolio management tool **

*\* this email brought to you by ✓ http://instantcheckmark.com ✓ **

**Comment by Uepsilon** [comment]
Wasserbomben pro (bitte auch noch [damit](http://www.amazon.de/Playtastic-Wasserbomben-Set-Praktische-F%C3%BCllhilfe-Ballons/dp/B005RXINQI), sonst geht das nicht schnell genug ;) 

Die Poolkanonen wären geil wenn wir einen Pool hätten, sonst sind die wenig Zweckgemäß.

Achja, [DAS](http://www.amazon.de/Living-Point-Schneeball-Katapult-Wasserbomben-Schleuder-Solo-1-Mann-Bedienung/dp/B000A3I23Y) brauchen wir noch xD

**Comment by colszowka** [comment]
@koos Please do not accidentally order [these](http://www.amazon.de/Stinkbomben-Schwarze-Schachtel-Extremer-Gestank/dp/B00915RJH2) instead. _For excercise and amusement I recommend checking out the product reviews though_

**Comment by erdnusskeks** [comment]
What about Rasensprenger? Could be quite refreshing - and not that expensive (about 20,- €).
Choose your favourite! : )
http://www.youtube.com/watch?v=9DCT8rRLceI

**Comment by jhilden** [comment]
Rasensprenger sounds good.  Does anybody have one?   Otherwise we'll try to get one on Friday.

**Comment by jhilden** [comment]
I checked with the venue, and they have only exactly **1** water faucet in the middle of the main hall.  This would have to be shared between the coffee car (#17) and any sort of water fun.  So maybe a Rasensprenger and a Planschbecken.

**Comment by raucao** [comment]
Wouldn't we have to use a fire hydrant anyway?
