### ISSUE TITLE
Ice cream (truck)

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#48]
If the weather is going to stay as sunny, some ice cream would defintely be nice at the camp.

Could anybody do some research on how we could get an ice cream truck to drive by the venue, or what it would take to get a big freezer with ice cream?  That would be awesome.

**Comment by moonglum** [comment]
I asked [cafe plati](http://www.cafeplati.de) for a price and availability. I think Saturday afternoon would be a good timing? :smile: :ice_cream:

@jhilden Where can I find the current number of people that bought a ticket?
