### ISSUE TITLE
Teardown/clenaup (on Sunday)

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#51]
The camp hasn't even started, but I'm already opening this issue for people to help tearing everything down and helping to clean up the venue on Sunday when everything is over (sometime after 5pm).

Stuff that will need to be done:
- dismount the Richtfunk equipment (at the venue and at the FH)
- clean the hall with the Kärcher thing they have
- tear down the audio equipment
- wifi equipment
- bring chairs and Biertischgarnituren back
- clean up the kitchen
- prepare the drink crates for pickup
- ...

So, who's in?

**Comment by raucao** [comment]
Count me in.
