### ISSUE TITLE
Wireless Abbau

### ISSUE THREAD

**Issue by badboy** [railscamp/railscamp-germany-2013#53]
Aus der FH muss mit:
- [x] Cisco-Router
- [x] 30m Kabel
- [x] PoE-Adapter
- [x] Richtfunkantenne

Dazu:
- [x] 2. Richtfunkantenne
- [x] 30m Kabel aus den Hallen
- [x] PoE-Adapter

Zeug aus den Abenteuerhallen bereits abgebaut und vorerst im Auto verstaut.

/cc @koos, @thegcat, @eimann

**Comment by koos** [comment]
@thegcat - sollen wir uns um 12 an der Bib treffen? http://goo.gl/maps/cSrLo

**Comment by thegcat** [comment]
Ich mache mich jetzt auf den Weg zur Bottmühle, können uns da oder dann an der FH treffen.

**Comment by koos** [comment]
Ich bin um 12 an der FH

**Comment by thegcat** [comment]
So, bald habe ich alles, @badboy wann kommt das wohin?

**Comment by badboy** [comment]
Also im Büro ist jemand. Du kannst vorbeikommen, wenn du willst. Ich geb dir eben die Nummer per SMS durch, ungefähre Zeit?

**Comment by thegcat** [comment]
Bin aktuell noch in Köln, sagen wir lieber morgen falls morgen jemand da ist. Kannst auch gerne meine Nummer weitergeben/mir die Nummer des Büros einfach geben.

**Comment by badboy** [comment]
Wie ich hörte, alles wieder in Dortmund angekommen. Danke.
