### ISSUE TITLE
Pick up stuff from the venue

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#56]
We still have a couple of things at the venue that we couldn't take with us yesterday:
- fatboys & Liegestühle from AdCloud
- some remaining drink crates
- wifi hardware
- etc.

Is there by chance any hero with a car that could pick up those things tomorrow or Wednesday and bring them to the AdCloud and Railslove offices?

**Comment by larsvegas** [comment]
AFAIK there is also a TV-Screen Fan of Adcloud.
@timbuchwaldt may you give your infos?!

I am not able to pick the stuff up for myself (sorry) anyone else maybe?

**Comment by jhilden** [comment]
Since nobody could be found, @namxam and I will rent a Flinkster car tomorrow at 10:00 and get the stuff.  We will first drive to the Railslove office and then to AdCloud.  Can I have a contact person + mobile number at AdCloud and some help when we arrive there (between 11:00 and 12:00)?  @larsvegas or @timbuchwaldt ?

**Comment by larsvegas** [comment]
Ring the bell on the 6th floor, and bring the stuff to the fifth. Somebody
(Sebastian/Sascha/Verena/Alwin/Myself) will be there. @namxam got my mobile
number in case of problems. THANKS GUYS!

Lars

2013/7/30 Jakob Hilden notifications@github.com

**Comment by jhilden** [comment]
Unfortunately we had issues renting the Flinkster car, so we will try again tomorrow or Friday.
