### ISSUE TITLE
Finances, book keeping, budget management

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#6]
We need somebody to keep an overview over all the finances & budget.

@thilo already said that he can help with this

**Comment by thilo** [comment]
Do you have any numbers yet i can use?

**Comment by jhilden** [comment]
I shared a Google Docs spreadsheet with the costs for the venue with you.  We don't really have any solid numbers beyond that, yet.

**Comment by thilo** [comment]
Can I see the contract details? to get a clue what is included to come up what else to expect cost wise.
