### ISSUE TITLE
Sponsors

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#7]
We need one or more persons taking care of finding sponsors

[] creating a sponsor package
[] work with the @eurucamp people on joint sponsor packages
...

**Comment by koos** [comment]
I could do that.

**Comment by raucao** [comment]
Go for it! Maybe create a Titanpad for brainstorming the package types etc, so we can help you.

**Comment by koos** [comment]
http://titanpad.com/BSc5bPt5S3

On May 27, 2013, at 3:36 PM, Sebastian Kippe notifications@github.com wrote:

> Titanpad

## 

Jan Kus

Railslove GmbH
An der Bottmühle 5, 50678 Cologne, Germany  

Mobile +49 (0) 179 13 53 53 9
Twitter @koos

Registergericht: Amtsgericht Köln, HRB 70843  
Geschäftsführer: Michael Bumann, Jan Kus, Tim Schneider

*\* We're proud of building: http://dealbaseapp.com - a web based deal tracking and portfolio management tool **

*\* Visit Cologne for a one week hack-tech-biz-creativity festival this year! June 17th - 23rd. http://interactive-cologne.com **

*\* this email brought to you by ✓ http://instantcheckmark.com ✓ **

**Comment by raucao** [comment]
\o/

**Comment by jhilden** [comment]
As you can read in the Titanpad (link above), we decided on the following sponsor packages:
- Individual Sponsor Package:  200€
- Small Company:  500€
- Serious Sponsor:  1000€

Plus some "Sachsponsor" Packages, where we know the concrete amounts.

**Comment by Uepsilon** [comment]
As i was surfing the new page, i found it quiet disturbing that sponsor-links open in the same window instead of creating a new one? Is this by purpose? Otherwise I would fix that ;)

**Comment by raucao** [comment]
That's a _very_ old UX discussion. ;)

I like it that way. If I want to open a new window, I do that myself. I don't like websites forcing browsing behavior on me. That said, others don't. You obviously belong to that group.

I for my part frankly don't even care, though. So, if you think it's better,  just do a PR, and someone will either merge directly or start a discussion on the PR.

**Comment by Uepsilon** [comment]
fair enough

**Comment by thegcat** [comment]
IIRC the W3C recommendation is to not open links in new windows/tabs as a general rule, and to somehow mark them/inform the user that a new window will open if he clicks on the link if one wants use extra-window links nonetheless.

**Comment by raucao** [comment]
This is where the party's at now: #35 ;)

**Comment by jhilden** [comment]
I started to collect the invoicing addresses of our sponsors here: https://docs.google.com/document/d/1QMQMwFKnWUNSbaOLrioxdE0DQTHKr40RMceZbl0Eehg/edit?usp=sharing (request access if you need it)
I guess we could start sending out invoices now, or?

**Comment by thilo** [comment]
Put it on my todo list, will start sending invoices soon.

**Comment by thilo** [comment]
Hey can i get the emails please of sponsors so that i can sent them their invoices?

**Comment by RmMsr** [comment]
Requested access to 2013 sponsors list for reuse in 2014.

**Comment by jhilden** [comment]
"access granted" :unlock:
