### ISSUE TITLE
Ticket sales

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#8]
We need somebody to take care of ticket sales.  Find a partner for selling the tickets, implement the solution, etc.

**Comment by raucao** [comment]
We used Eventbrite for our last 5apps hackathon. That was a pretty nice solution. And we can just integrate the widget on the site.

**Comment by koos** [comment]
Support our local startup: http://www.loudplaces.com/
Prices are more than 1 EUR cheaper than Eventbrite and Amiando
We're using it for interactive-cologne

**Comment by raucao** [comment]
It doesn't seem like it has good management for event organizers. There's not even _any_ information about that on the whole site. At least I couldn't find any. Sometimes it's worth to pay that 1 EUR more. ;)

**Comment by koos** [comment]
I don't say it's the best choice, but hey, it works, you can buy a ticket, there are vouchers... 
but no pressure :)

On May 27, 2013, at 3:31 PM, Sebastian Kippe notifications@github.com wrote:

> It doesn't seem like it has good management for event organizers. There's not even any information about that on the whole site. At least I couldn't find any.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Jan Kus

Railslove GmbH
An der Bottmühle 5, 50678 Cologne, Germany  

Mobile +49 (0) 179 13 53 53 9
Twitter @koos

Registergericht: Amtsgericht Köln, HRB 70843  
Geschäftsführer: Michael Bumann, Jan Kus, Tim Schneider

*\* We're proud of building: http://dealbaseapp.com - a web based deal tracking and portfolio management tool **

*\* Visit Cologne for a one week hack-tech-biz-creativity festival this year! June 17th - 23rd. http://interactive-cologne.com **

*\* this email brought to you by ✓ http://instantcheckmark.com ✓ **

**Comment by raucao** [comment]
Proper widget for our site? Ticket returns? Waiting list?

I'll have a look at it, but I won't sign up for sth that doesn't tell me what it does. ;)

**Comment by koos** [comment]
> Proper widget for our site?
> 
> ✓
> Returning tickets?
> 
> ✓
> Waiting list?
> 
> donno
> —
> Reply to this email directly or view it on GitHub.

*\* this email brought to you by ✓ http://instantcheckmark.com ✓ **

## 

Jan Kus

Railslove GmbH
An der Bottmühle 5, 50678 Cologne, Germany  

Mobile +49 (0) 179 13 53 53 9
Twitter @koos

Registergericht: Amtsgericht Köln, HRB 70843  
Geschäftsführer: Michael Bumann, Jan Kus, Tim Schneider

*\* We're proud of building: http://dealbaseapp.com - a web based deal tracking and portfolio management tool **

*\* Visit Cologne for a one week hack-tech-biz-creativity festival this year! June 17th - 23rd. http://interactive-cologne.com **

**Comment by moonglum** [comment]
We could also ask the [nicer](https://www.getnicer.com) guys, what we would need to pay for their systems. They also handle the stuff during the event like an app with the up to date schedule etc. It worked great at RailsBerry.

It's invite-only, but I guess we clarify :wink:

**Comment by koos** [comment]
nicer is nice... but

-> support your local startup

#justsaying

On May 27, 2013, at 9:01 PM, Lucas Dohmen notifications@github.com wrote:

> We could also ask the nicer guys, what we would need to pay for their systems. They also handle the stuff during the event like an app with the up to date schedule etc. It worked great at RailsBerry.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Jan Kus

Railslove GmbH
An der Bottmühle 5, 50678 Cologne, Germany  

Mobile +49 (0) 179 13 53 53 9
Twitter @koos

Registergericht: Amtsgericht Köln, HRB 70843  
Geschäftsführer: Michael Bumann, Jan Kus, Tim Schneider

*\* We're proud of building: http://dealbaseapp.com - a web based deal tracking and portfolio management tool **

*\* Visit Cologne for a one week hack-tech-biz-creativity festival this year! June 17th - 23rd. http://interactive-cologne.com **

*\* this email brought to you by ✓ http://instantcheckmark.com ✓ **

**Comment by jhilden** [comment]
Requirement:  The solution needs to be able to withstand traffic peaks.

**Comment by thilo** [comment]
I could also ask paul if we can use tito for that as well, would lower the setup as we are using it for eurucamp and jrubyconf eu already. right now we only pay 4% on credit card transactions or paypal fees.

**Comment by koos** [comment]
Loudplaces offers Interactive Cologne: 1 EUR + 5% and we have 25% off. That means: instead of 2.25 for a 25 EUR ticket, 1.68 - which is a great deal. I can arrange the same deal if needed.

On May 28, 2013, at 10:04 PM, Thilo Utke notifications@github.com wrote:

> I could also ask paul if we can use tito for that as well, would lower the setup as we are using it for eurucamp and jrubyconf eu already. right now we only pay 4% on credit card transactions or paypal fees.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Jan Kus

Railslove GmbH
An der Bottmühle 5, 50678 Cologne, Germany  

Mobile +49 (0) 179 13 53 53 9
Twitter @koos

Registergericht: Amtsgericht Köln, HRB 70843  
Geschäftsführer: Michael Bumann, Jan Kus, Tim Schneider

*\* We're proud of building: http://dealbaseapp.com - a web based deal tracking and portfolio management tool **

*\* Visit Cologne for a one week hack-tech-biz-creativity festival this year! June 17th - 23rd. http://interactive-cologne.com **

*\* this email brought to you by ✓ http://instantcheckmark.com ✓ **

**Comment by thilo** [comment]
Maybe go even further and ask if they like to donate their share of the costs , or make an agreement that they are listet as ticket sponsors. current offer means more than 6% of ticket.

**Comment by koos** [comment]
I can do that.
On May 29, 2013, at 8:05 PM, Thilo Utke notifications@github.com wrote:

> Maybe go even further and ask if they like to donate their share of the costs , or make an agreement that they are listet as ticket sponsors. current offer means more than 6% of ticket.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Jan Kus

Railslove GmbH
An der Bottmühle 5, 50678 Cologne, Germany  

Mobile +49 (0) 179 13 53 53 9
Twitter @koos

Registergericht: Amtsgericht Köln, HRB 70843  
Geschäftsführer: Michael Bumann, Jan Kus, Tim Schneider

*\* We're proud of building: http://dealbaseapp.com - a web based deal tracking and portfolio management tool **

*\* Visit Cologne for a one week hack-tech-biz-creativity festival this year! June 17th - 23rd. http://interactive-cologne.com **

*\* this email brought to you by ✓ http://instantcheckmark.com ✓ **

**Comment by zakx** [comment]
It doesn't seem like it would fit your event, but if you're looking into setting something up on your own, at CCC we're using https://github.com/CCCO/c4sh_preorder and https://github.com/CCCO/c4sh as a complete cashdesk solution. We also have some nice hardware we could borrow you, including cash counting appliances.

![open-side](https://f.cloud.github.com/assets/628602/598428/8fffe1ca-cc2c-11e2-933d-c170e081b745.jpg)

**Comment by raucao** [comment]
Since nobody else acted so far, I set up everything we need with Eventbrite and already put the widget on the new (as of yet unpublished) website.

I vote for starting ticket sales next Friday (June 14) at 4pm. If somebody thinks that's a bad time for whatever reason (hopefully out of experience), please speak up! Frankly, I myself have no idea, and I can't remember when we opened the registration last time.

**Comment by thilo** [comment]
Great initiative, but do it on Monday. very few people a receptive to news on Friday afternoon. 

cheers

Thilo

**Comment by raucao** [comment]
Ok, thanks. Let's do it on Monday then. 4pm alright?

**Comment by thilo** [comment]
how is ticket sale going so far?

**Comment by jhilden** [comment]
The first 100 tickets are almost gone.  But we could really use another marketing push by everybody if we want to reach 200 participants.

**Comment by raucao** [comment]
I think we should write another invitation and send it out directly to user groups etc. We also didn't email the people registered on railscamp.de yet.

**Comment by thilo** [comment]
Can somebody transfer the money to the vereins account please?

KNR: 1008381756
BLZ: 120 300 00

IBAN: DE44120300001008381756 
BIC: BYLADEM1001

**Comment by raucao** [comment]
It will be automatically transferred to that account 3 days after the event.
