### ISSUE TITLE
Wifi

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#9]
We need one or more person to take care of a a working wifi at the venue.

@rubyberlin might have/buy some wifi equipment

We might also be able to talk to the Cologne CCC people who organize the internet at the SIGINT.

**Comment by moonglum** [comment]
I contacted zakx.

**Comment by moonglum** [comment]
I contaced Tom from the organisation team of evoke (same location, therefore probably same problems)

**Comment by moonglum** [comment]
The cites will be in German, sorry :wink: 

Tom (from evoke orga):

> haha, ach ihr seid das :) wir haben schon von der abenteuer halle von euch gehört :)
> wir haben das glück, dass uns viprinet sponsort (www.viprinet.com/). die bringen immer einige umts karten mit.
> deren geräte können mehrere leitungs, oder auch umts und dsl zusammen bündeln.
> 
> ansonsten nehme ich auch mal den stephan mit in cc, der leitet die evoke netzwerk abteilung ;)
> den kennst du evtl auch noch aus berlin, der war zu der zeit da und wir waren zusammen in der cbase etc...

Stephan (from evoke networking):

> die Welt ist klein :) Das mit dem Internet in der Abenteuerhalle ist in der Tat alle andere als einfach. Wir haben das Glück, dass wir von viprinet gesponsort werden, da der Inhaber selber in der Demoszene aktiv ist…ich glaube sonst ist das nicht so günstig. Am Ende werden da von Ihm dann ohne Ende UMTS und LTE-Verbindungen zusammengebündelt, das kostet ja meist auch Traffic und so.
> 
> Für WLAN-Equipment haben wir dieses Jahr wohl zum ersten Mal auch was vernünftiges, allerdings leihen wir das von einem Arbeitgeber von einem der Organisatoren. Ich habe aber mit den Jungs hier ein paar Worte gewechselt und die machten eine recht netten Eindruck (ist ja auch CCC-Umfeld, vielleicht hilft das): [nocpool](http://www.nocpool.eu)
> 
> Ansonsten hatte die "Next Level Conference" auch mal einen Kontakt zur Telekom um eine LTE-Flatrate für das Wochenende zu kriegen, da könnte ich nochmal nachfragen.
> 
> Am Ende ist halt die Frage was Ihr an Bandbreite braucht, freundet Euch besser mal mit sehr wenig an. Die Halle selber hat nur ein 4 Mbit DSL-Anschluss mit sowas wie 500 k Upstream. Es gibt am Anfang der Straße wohl 100 Mbit Glasfaser aber nicht bis zur Halle. Reden mit Netcologne war in den letzten Jahren da SEHR unkooperativ, und auch eine Kontaktaufnahme zu den Nachbarn war eher nicht erfolgreich letztes Jahr. Sorry for the bad news :/

**Comment by moonglum** [comment]
So I contacted nocpool:

> Hey nocpool,
> 
> We're organizing a RailsCamp in Cologne (26. to 28. of July) in a location without WiFi. Some guys told us, that you help non-profit events – and our event is non-profit! We'll have 200 people longing for an Internet connection there. Could you help us out with the WiFi equipment? If so, how much would it be?
> 
> You can find our current website here (Yep, still working on it ;) ):
> http://railscamp.github.io/railscamp-germany-2013/
> 
> Kind Regards,
> Lucas

They answered:

> hi,
> what would you need? and when is the event?
> the default kit is ~20 cisco APs + a vWLC to control them.
> br
> kay

He somehow didn't see the date, I will just write the date again. But is the kit ok for us? I have no idea! Sounds good to me. @skddc @jhilden – do you know that? And do you know how to configure a vWLC?!

**Comment by raucao** [comment]
I have no idea. Please ask them if it's simple enough for a non-specialist to operate that stuff. Or we have to find someone who knows their network systems well enough. Probably also possible. But at least we have to know so we can factor that in.

**Comment by moonglum** [comment]
I wrote:

> Hi,
> 
> The event will be from the 26. to 28. of July. The amount of APs sounds to be more than enough (10 people per access point – that's a really good ratio). Is this easy enough to set up for us (programmers)? Or do we need a professional network administrator?
> 
> Best Wishes,
> Lucas

**Comment by zakx** [comment]
Hey,

CCC bought some of the terrific Unifi APs and lends them to CCC events (and those close to that, railscamp may apply). You can find more information about that at https://eventwlan.cccmz.de/, and the upside is, that you don't need to put a company logo anywhere for that.

Downside is of course, that you still need to solve your upstream problem.

**Comment by moonglum** [comment]
Here is the answer from the nocpool guys:

> Hello
> 
> You wil need a server to host the vWLC virtual machine, this must run ideally ESXi. We can supply you with a trial of vWLC which will run 60 days.
> 
> Along with that you'll need PoE capable 802.3af compliant switches to power the access points.
> 
> What date would you need the kit at and when would it be returned?
> 
> Thanks,
> 
> nat.

@zakx Sounds awesome :smile: We can also try that! You have to enter the name of an ERFA/Chaostreff in the registration form though. Can we use CCCC and add you as our "man from the ERFA"? :wink: 

I also [asked Mateus](https://twitter.com/moonbeamlabs/status/341881523240316928) from our user group if he can help us with LTE. He works for Deutsche Telekom :wink: //cc @seanlilmateus

**Comment by zakx** [comment]
@moonglum Tobi is also a member of C4, maybe that would make more sense if he's on the event anyway? :)

**Comment by jhilden** [comment]
What's the current status for this?  I think we need to start acting soon, especially on getting the internet connection, I think with the wifi we are already on a good track.

ccing @timbuchwaldt, he might be able to help us

**Comment by seanlilmateus** [comment]
von mir gibt leider nichts Neues, irgendjemand hat mal davon erzählt das ein Kollege von mir die Hotspots besorgen hat. Gibt da en Name?

**Comment by timbuchwaldt** [comment]
I have compiled a list of hardware we would need if we want to build this on our own and give it to Ruby e.V. afterwards. Essentially it's just what CCCMZ uses. Without any discounts we speak about 1.5k+ € for APs (3\* 3-pack UniFi Pro), not including the WiFi-controller, router + switches.

If there is the slightest chance of getting this from CCCMZ I would reaaaaally prefer that.

**Comment by zakx** [comment]
> Hallo zakx,
> vielen Dank für Deine Reservierungsanfrage für das EventWLAN.
> Wir werden umgehend Deine Anfrage bearbeiten und Dir mitteilen,
> ob die Reservierung des System I zu dem gewünschten
> Zeitraum vom 26.07.13 bis 28.07.13 klappt.

**Comment by timbuchwaldt** [comment]
Super gut! Danke @zakx

**Comment by zakx** [comment]
CCCMZ reserved their UniFis for you. As it is not a CCC event, they're asking for a donation in accordance to your event's budget (which will be used to expand the AP lending offer, so it's a good thing!). You may also need to pay for transport of the flight case from/to Mainz, but maybe we can do something about that (no promises though).

Please let me know if you can agree to that ASAP.

**Comment by timbuchwaldt** [comment]
From my side, this would be perfect! :)

**Comment by moonglum** [comment]
Ok, I contacted nocpool to tell them that we don't need their help anymore.

**Comment by raucao** [comment]
Let's do it!

@timbuchwaldt You're the one operating it in the end? We should assign this issue to the person who knows how that stuff works, so other people can refer to him or her.

**Comment by timbuchwaldt** [comment]
@skddc Yes, I am. And I know how the stuff works :) I will have my vacation a little earlier than camp-start for setting up

@zakx Will we get the cabling and everything from CCCMZ, too?

**Comment by raucao** [comment]
@timbuchwaldt Ok, cool!

**Comment by thilo** [comment]
If you still need to shoot internet from somewhere we can still provide http://www.ubnt.com/airmax#nanobridgem or something similar from Berlin.

**Comment by timbuchwaldt** [comment]
Thanks @thilo  - We will come back to you if situation is clearer. Currently we hope to get a bunch of DSL lines in the building which could be bundled.

**Comment by timbuchwaldt** [comment]
So, we sent CCMZ the "order-sheet" this week. We got everything they have - all cabling + all APs, including one for outdoor Wifi. Can I let them mail the box to Railslove, @jhilden / @koos ?

**Comment by jhilden** [comment]
Sure thing @timbuchwaldt :

Railslove GmbH
Jan Kus
An der Bottmühle 5 
50678 Cologne 
Germany

**Comment by timbuchwaldt** [comment]
So.. the equiment magically made it to C4. I will get it on friday together with @zakx . Due to a snafu we might not have all LAN-cables. We will have to buy the lacking ones. If anyone has spare cables: Bring them.

I will bring a roll of cat5e and crimping equipment for 2-4 cables

**Comment by raucao** [comment]
It's working great. Good job!

**Comment by jhilden** [comment]
@timbuchwaldt will take care of the paperwork, bank account number, etc. for the donation to the CCC Mainz.

**Comment by jhilden** [comment]
@timbuchwaldt this is the information I got from @thilo :

> Bzgl. Spende CCC Mainz, das geht offizel leider nicht, das würde uns da
> Finanzamt als nicht Satzungsgemäß ankreiden. Können die uns einfach ne
> Rechnung für die Miete der WlanHardware stellen?

Can you take care of asking them?

Also,  does anybody have an idea for a cheap way of shipping the big box to Mainz?

**Comment by timbuchwaldt** [comment]
Wifi is returned safely to CCMZ. If anything misses we will be told by them, but i don't see that :)
Regarding the donation:
CCCMZ is a "gemeinnütziger Verein" and therefore can't write invoices. They checked with their Kassenwart, they can write us a receipt for a normal donation.

**Comment by raucao** [comment]
Uh, Ruby Berlin e.V. is the same and we're writing invoices to sponsors. @thilo?

**Comment by thilo** [comment]
Das ist so nicht richtig, meines Wissens Auch ein gemeinnutziger Verein 
darf wirtschaftliche Einnahmen und Ausgaben haben, die muss er halt 
versteuern.
Ich hab mich schon einige Stunden mit Steuerberater und 
Vereinsvorständen hingesetzt um diese Fragen zu klären.

Hier mein privaten Notizen zu dem Sachverhalt.

https://docs.google.com/document/d/16RvwUHpzLW1DgMy877IteUonsFBgmElrsfz_Dpf6J8A/edit?usp=sharing

Besten Gruß
Thilo

**Comment by jhilden** [comment]
@timbuchwaldt kannst du nochmal nachhaken, wie wir das mit dem CCC Mainz jetzt am besten machen können?  Ich würde denen schon gerne was geben.

**Comment by timbuchwaldt** [comment]
@jhilden Mail is raus :)
